### ISSUE TITLE
vendor directory should be removed

### ISSUE THREAD

**Issue by weinong** [Azure/acs-engine#1084]
**Is this a request for help?**:

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---
Issue
**What version of acs-engine?**:

---
HEAD

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:
The vendor directory is causing downstream project build conflict between downstream's imported package and acs-engine's imported package.

**What you expected to happen**:
as long as acs-engine does not include vendor packages, downstream project can resolve dependencies to download and build using downstream's vendoring.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
Fix is simple. Delete vendor directory and add /vendor to .gitignore.

**Comment by seanknox** [comment]
Yeah, go's dependency management drives me a little batty because of problems like this. When glide was first introduced Cole [advocated for keeping `vendor/` checked in](https://github.com/Azure/acs-engine/pull/623#issuecomment-301639165). Let's ask a few other experienced gophers their opinion on this issue. @kris-nova @technosophos thoughts on gitignoring `vendor/` in this repo due to version conflicts with downstream projects who consume it?

**Comment by weinong** [comment]
Specifically, the error I got when converting RP to glide was 
`cannot assign "acsrp/vendor/github.com/Azure/acs-engine/vendor/github.com/Azure/azure-sdk-for-go/arm/compute".VirtualMachineScaleSetListResult to vmssList (type "acsrp/vendor/github.com/Azure/azure-sdk-for-go/arm/compute".VirtualMachineScaleSetListResult)`

**Comment by technosophos** [comment]
We tend not to commit our vendor directory. The above error is very likely just that the version was not specified in the glide.yaml file.

**Comment by anhowe** [comment]
Where is the alternate location for the vendor files?  How do we protect our project, if a vendor owner deletes their project, or marks it as private?

**Comment by weinong** [comment]
discussed with Matt offline. No changes required for acs-engine. The downstream (RP) will use glide to flatten the vendor packages
