### ISSUE TITLE
Difficulties provisioning kubernetes cluster in secure environment

### ISSUE THREAD

**Issue by gedgar** [Azure/acs-engine#1198]
**Is this a request for help?**: Yes.
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Issue

---

**What version of acs-engine?**: 
Not sure. acs-version is printing 'unset (unset)' and I'm having issues building a new deployment image to test the latest version. 

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
azureuser@k8s-master-41051073-0:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.6", GitCommit:"7fa1c1756d8bc963f1a389f4a6937dc71f08ada2", GitTreeState:"clean", BuildDate:"2017-06-16T18:21:54Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"linux/amd64"}

**What happened**:
Manual changes to configuration files are being lost.

**Anything else we need to know**:
 Bear with me here, my experience with Azure/acs-engine/kubernetes is pretty limited and I recently took over this project from a colleague of mine. We're trying to deploy a Kubernetes cluster in a secure Microsoft environment and due to security policy, these VMs will have limited access making provisioning them with standard Azure services prohibitive.

It was decided to build and update the VMs outside of this environment, delete them while preserving the disks, and recreate them inside of the secure environment using the original disks. Any connectivity to Azure services would be facilitated through a proxy to ensure secure access. 

We need to create and update the boxes - from defaults - in CorpNet, because that can reach the Internet. However, the private IPs of our VMs change when we recreate the boxes in the subnet that faces the secure environment, so we're trying to manually tweak configuration files that have IP addresses hard-coded in them:

/opt/azure/containers/kubelet.sh
/etc/kubernetes/manifests/kube-apiserver.yaml
/etc/default/kubelet
/var/lib/kubelet/kubeconfig

The problem we're seeing is that our changes to these files are getting blown away when the boxes come back up with the new private IPs. As a result, the kubelets are unable to talk to API server because these configs point to the original IPs.

I'm hoping there's a simpler solution for what we're trying to accomplish - Any help would be greatly appreciated.

**Comment by lachie83** [comment]
Hi @eddyg3. 

These are blown away as cloud-config will re-run when the node is rebooted. Can you please let me know what you're changing in each file and I will let you know if we support those configurations? 

The solution here would be to use configure the changes inside your cluster-defintion and then deploying that template. See https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md for a list of configurable options.

**Comment by eddyg3** [comment]
Hi @lachie83,

Thank you for your response. FWIW, I can confirm that we're now running v.0.5.0 (had to work around #1160).

- Because this environment doesn't have access to the internet, we're trying to modify `/etc/systemd/system/kubelet.service` by adding `--env-file /etc/kubernetes/proxy.env` to the kubelet's `docker run` command to allow our kubelet service to communicate with Azure's API.

- Additionally, because the private IPs of our VMs change when we recreate them (from disk) in the EML(Enterprise Management LAN)-facing subnet, we're trying to update files which have the IP address for the API server hardcoded in them. Specifically, we're trying to change `10.240.255.5` to `10.51.223.10` in `/opt/azure/containers/kubelet.sh`, `/etc/kubernetes/manifests/kube-apiserver.yaml`, `/etc/default/kubelet`, and `/var/lib/kubelet/kubeconfig`.

Given that cloud-config re-runs on boot, tweaking those hardcoded IP addresses obviously isn't the way to go. Please correct me if I'm wrong, but after going through the configurable options for the cluster it looks like we should have our masterProfile point to the master's eventual subnet (10.51.223.0/25) and set the firstConsecutiveStaticIP to the master's eventual private IP (10.51.223.10), though I'm worried that we won't be able to deploy directly to this secure (limited access, no internet) subnet.

Thanks again for replying - any help is much appreciated. 

Regards,
Gary

**Comment by eddyg3** [comment]
@lachie83 Please let me know when you have a chance to review my previous reply. 
cc: @sauryadas @colemickens 

Thank you.

**Comment by lachie83** [comment]
Hi Gary.

> Because this environment doesn't have access to the internet, we're trying to modify /etc/systemd/system/kubelet.service by adding --env-file /etc/kubernetes/proxy.env to the kubelet's docker run command to allow our kubelet service to communicate with Azure's API.

Okay. Yes currently we have no provision for adding a proxy.env file so your best bet is fork the repo and make the changes to acs-engine to add that file and the corresponding options in kubelet.

> Additionally, because the private IPs of our VMs change when we recreate them (from disk) in the EML(Enterprise Management LAN)-facing subnet, we're trying to update files which have the IP address for the API server hardcoded in them. Specifically, we're trying to change 10.240.255.5 to 10.51.223.10 in /opt/azure/containers/kubelet.sh, /etc/kubernetes/manifests/kube-apiserver.yaml, /etc/default/kubelet, and /var/lib/kubelet/kubeconfig.

Yes if you should be able to provision into a existing block and I think as long as your sort out the proxy configuration you should be able to redeploy.
