### ISSUE TITLE
kubernetes/azure-cloud-provider: Enable annotation to specify subnet to create Azure load-balancer

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#1296]
**Is this a request for help?**: yes

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature

---

**What version of acs-engine?**: All

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

Currently all Azure Load balancers are provisioned in the same subnet as the master VMs.

**What you expected to happen**:

Allow an annotation to specify which subnet you wish the Azure loadbalancer to be created in

**How to reproduce it** (as minimally and precisely as possible):

Create a Kubernetes service resource of type load balancer on a cluster that has master and agent nodes in different subnets. The Azure LB will be provisioned in the master subnet

**Anything else we need to know**:

**Comment by lachie83** [comment]
cc @itowlson @slack @jdumars

**Comment by slack** [comment]
I believe there is a further restriction that LBs can only be provisioned in the `primaryAvailabilitySet` which is hard-coded in the cloud provider config. Would be nice to tackle that restriction at the same time.

**Comment by itowlson** [comment]
@slack We may have to - I've got the subnet annotation working, but if I try to deploy two internal LBs on different subnets, I get errors from Azure about "Network interface [nic_id] references more than one load balancer of the same type (internal or public): ... Only one internal and one public load balancer are allowed per availability set."  So if we don't support multiple availability sets then the feature is limited to to "you can control which subnet the internal LB is in but you can't have internal LBs in different subnets."  @lachie83 I assume that isn't an acceptable limitation?

**Comment by itowlson** [comment]
@slack It looks like there is a problem with availability sets anyway - if I have multiple agent pools, and create a deployment on the secondary agent pool, I can't expose that as a service.  It gets assigned an IP address and port on the load balancer, but the LB's backend pool is the primary agent pool, so requests to the LB never get routed to the deployment.  It seems like we should be allowing one internal and one external LB per agent pool (we can't allow more because of Azure restrictions it seems): the front end IPs can be controlled as to subnet, but controlling that at the service level feels dubious -- if I move the agentpool1 internal LB from subnet1 to subnet2 then that affects _all_ services in agentpool1.  cc @lachie83 @jdumars - do we need a wider discussion about the desired behaviour here?
