### ISSUE TITLE
Install image-gc configurable will sane defaults

### ISSUE THREAD

**Issue by lachie83** [Azure/acs-engine#1374]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): Feature request

---

**What version of acs-engine?**: All

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** Kubernetes

**What happened**:

Docker images fill the agent filesystem

**What you expected to happen**:

Setup sane defaults for and allow user-specified configuration image-gc eg.

`-image-gc-high-threshold=50 --image-gc-low-threshold=30`

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by lachie83** [comment]
cc @nalthoff

**Comment by lachie83** [comment]
@nalthoff has volunteered to take a look at this

**Comment by lachie83** [comment]
Kubelet options here -- https://kubernetes.io/docs/admin/kubelet/

**Comment by nalthoff** [comment]
Thanks @lachie83 I'm on it!

**Comment by jackfrancis** [comment]
@nalthoff if you wanted to put together a solution, feel free to refer to the way `--node-status-update-frequency` was implemented in this PR:

https://github.com/Azure/acs-engine/pull/892/files

Let me know if you have any more questions!

**Comment by nalthoff** [comment]
Thanks @jackfrancis . I'll take a look and let you know. Appreciate the support!

**Comment by nalthoff** [comment]
@jackfrancis @lachie83  A few questions. 
1. What would you consider "Sane" in this case? It looks like the defaults are 85/80.
2. Do you think this should be a configurable value that the users can set with the input json file or for now just set it to a different agreed upon value than the 85/80? I was thinking it could be an optional configurable value, but wanted your thoughts.

**Comment by jackfrancis** [comment]
I think we should defer to the defaults for the particular k8s version to determine what "sane" is. Could you do some cursory research to verify that 85/50 hasn't changed in the last several minor releases? (say, from 1.5 through current HEAD, which should be a rough predictor of 1.8) If the default vals have remained static across releases, we can probably just set those defaults generally, so that all versions of k8s that acs-engine generates templates for have them.

And we should definitely make these configurable in terms of having our own opinions about how to override them.

So, in summary:

- add `-image-gc-high-threshold` and `--image-gc-low-threshold` as command line options that we pass to the kubelet
- make the values for those options the k8s defaults so that if users don't explicitly declare override values we essentially maintain the existing behavior of deployed k8s clusters
- add configuration vectors to the api model's `kubernetesConfig` that allows users to add override values for the above
- incorporate the new config vectors into existing documentation with some simple guidance as to when it would make sense to override these values, and some recommended override values for representative scenarios

Going forward, we should definitely be open to changing the default values away from the k8s defaults if it makes general sense for our cluster behaviors. Additionally, we should decompose the cluster configuration conditions that might make inform why we would want custom values, and consider expressing that in code as dynamic conditional config (e.g., if vm size is smaller than size X, set to this, or if node count is greater than n, set to this; i.e., whatever operational conditions we can identify that relate to overriding gc behavior).

Thanks again!

**Comment by jackfrancis** [comment]
If the above comment wasn't clear, what I'm advocating is that we create a single PR that introduces the additional config with the ks8 defaults, and then we refine how we dynamically assign that configuration in subsequent, iterative PRs.

**Comment by nalthoff** [comment]
Thanks. I've got more than enough to go on for a bit here. Appreciate the support.

**Comment by lachie83** [comment]
I'm in agreement with @jackfrancis on this. Thanks for digging in @nalthoff

**Comment by nalthoff** [comment]
@jackfrancis it looks like the default for 1.5 and 1.6 were 90/80 and in 1.7 it was updated to 85/80.  I'm not sure how i could figure out when that was changed, but it doesn't seem to have changed much. It seems like 85/80 would be OK for all versions unless you think we need to match the k8s docs.

**Comment by nalthoff** [comment]
@jackfrancis I'm working through the steps outlined in the [code delivery](https://github.com/Azure/acs-engine/blob/master/docs/acsengine-code-delivery.md).md and I'm getting errors in "test-style", but as far as I can tell the errors are not related to acs-engine, but related to some of the plugins. Is that something I need to worry about? Just want to make sure I'm following the rules here...
