### ISSUE TITLE
Question: Does the Kubernetes networking model use an overlay network (Weave, Flannel)?

### ISSUE THREAD

**Issue by politician** [Azure/acs-engine#154]
What is the current networking model for Kubernetes on Azure?  Previous attempts involved using Weave or Flannel to create an overlay network were found to significantly affect performance due to limitations of Azure networking.

In particular,
1. Are pod IP addresses assigned from an overlay network?
1. Is the pod overlay network using GRE/VXLAN or is that still prohibited?  
2. If the overlay network uses Weave (sans "fast path"), has there been a recent replication of that [2015 performance benchmark](http://www.generictestdomain.net/docker/weave/networking/stupidity/2015/04/05/weave-is-kinda-slow/) for Weave on Azure?
3. It looks like [configuring the network to route Pod IPs](https://blogs.msdn.microsoft.com/stephgou/2016/07/11/kubernetes-cluster-automated-deployment-on-azure-first-step/) is an option.  Is the the networking model configurable?  Can you point me towards more details on this approach?
1. Are there any recent benchmarks you can point out that examine Kubernetes networking performance on AWS vs Azure?

Thanks; I'd love to understand more about the current situation, but couldn't find any documentation on the composition of the networking model.

**Comment by colemickens** [comment]
Weave hasn't been used for some time. `azkube` used `flannel` and `kubernetes-anywhere` and `acs-engine` both use native Azure networking - the same way it works in GCE/AWS.

1, There is no overlay. The IPs are allocated from a subnet assigned to each node by apiserevr.

2. n/a

3. n/a

4. That's what we use now, but it's all automated because the `cloudprovider` implementation for Azure does it for you.

5. Not that I'm aware of.

**Comment by politician** [comment]
That's ideal.  Thanks for the update!
