### ISSUE TITLE
Kubernetes Credentials retrieval from API after cluster creation

### ISSUE THREAD

**Issue by vishal-biyani** [Azure/acs-engine#155]
I am not sure if this should go here or at [REST API specs](https://github.com/Azure/azure-rest-api-specs) but I am filing one for discussion if someone has encountered same issue earlier.

After setting up the Kubernetes cluster by calling ACS APIs the only way that is documented to access Kubernetes API seems to be to retrieve the ```kubeconfig``` and then connect with API using certs or interact via ```kubectl``` 

Is there a way to retrieve credentials so that using those it is possible to talk to Kubernetes API endpoint directly? Is/should there be an endpoint for retrieving the credentials so that there is no manual intervention.

**Comment by colemickens** [comment]
Yes, we plan to make a way of retrieving credentials through the API
instead of SCPing it from the master.

But why do you want something besides the KUBECONFIG file? Every Kubernetes
client I've seen accepts that file. If you look inside you'll find the
constituent pieces - the root CA public key, the client cert/key, etc.

Just trying to understand exactly what you're asking for.

**Comment by vishal-biyani** [comment]
@colemickens Thanks for quick response. Let's assume a use case of spinning up a new cluster and deploy an app right after that using Kubrnetes API let's say via Jenkins. I can SCP the Kubeconfig and use it but that's slightly more complex than an API call. Also in some cases I don't want to use kubectl and prefer API only.

**Comment by vishal-biyani** [comment]
@colemickens Is there any timeline or rough plan about when this could get implemented?

**Comment by anhowe** [comment]
This is out of scope for ACS-Engine.  As there is a workaround we are closing.  File this as a feature request here: https://github.com/Azure/ACS.
