### ISSUE TITLE
Feature request: Better API authentication mechanism

### ISSUE THREAD

**Issue by vishal-biyani** [Azure/acs-engine#159]
Currently, the way authentication works in ACS requires you to copy the kubeconfig file and then talk using certs. This is not the cleanest way IMHO and there should be a better API driven way of working doing authentication. I think we have enough examples already and I will talk about two alternatives that I can think of:

1) The Azure service principal itself as a way to authenticate - this is very similar to the way it is done in GCE. The service principal that is used for creating the cluster using Azure API can also be used to talk to Kubernetes API. I am assuming this would be possible by inserting a serviceAccount in Kubernetes and translating the authentication accordingly. 

2) Provide the bearer token over API. The bearer token can be retrieved from ```default``` service-account or can be created. GCE at the moment provides username/password to user in console.

I am no expert and there might be caveats in this proposal and not sure how it will work in Mesos/Swarm etc. But please feel free to comment accordingly.

**Comment by colemickens** [comment]
@vishal-biyani We've been thinking about this a bit...

In general, I think that `kubeconfig` is the standard, right way to talk to the cluster. Even in scenarios where a bearer token is used, it would likely be presented in the form of a `kubeconfig` file as this is the standard for all Kubernetes-related applications and libraries that I've seen.

(If you disagree with this assessment, I'm curious to hear more - particularly if others are doing something closer to what you want as an example)

That having been said, retrieving the `kubeconfig` file right now is an unwieldy process (uses SSH, has to happen on the machine that created the cluster, etc). Over time, we will likely expose that `kubeconfig` file through the ACS API (though that doesn't really change the mechanics of how the `kubeconfig` file is used though).

I think a better option longer-term would be to use OIDC support for AuthN in Kubernetes.

I have an example of how you can use OIDC with Azure AAD to do authentication to a Kubernetes cluster. https://github.com/colemickens/azure-ad-k8s-oidc-example This would actually let users get tokens that represent themselves, rather than service accounts, making RBAC policies easy.

Ultimately though, even Bearer auth with OIDC is done via `kubeconfig` normally. Though you could obviously pull the Bearer token out and use it directly with raw HTTP calls...

Let me know your thoughts about my thoughts here...

**Comment by anhowe** [comment]
Marking as P2 since Cole's OIDC model shows potential.  Overall I do agree that kubeconfig is the standard, and people coming from outside of Azure will be used to it.

**Comment by vishal-biyani** [comment]
@colemickens Thanks and what you propose is an excellent solution.

**Comment by anhowe** [comment]
FYI: this PR helps solve this: https://github.com/Azure/acs-engine/pull/479.

**Comment by colemickens** [comment]
MSI does not help with cluster authentication. MSI is about K8s -> ARM auth. Not user->k8s auth.

The relevant change here is around https://github.com/kubernetes/kubernetes/pull/43987
