### ISSUE TITLE
Remove service principal credential from k8s agent node

### ISSUE THREAD

**Issue by yangl900** [Azure/acs-engine#177]
Today by default we leave the SPN credential on k8s agent node. It seems not necessary (or I missed any scenario). The SPN has pretty powerful permission in control plane. For a better security model, i think we should only have the master node be able to get the SPN token.

**Comment by colemickens** [comment]
Kubelet uses it for self-labeling/identification today, but it could use a read-only SP for that. In order to do that though, we'd have to have two service principals which would be a change from the current api model. 

I think instead we should try to support this via MSI so that mess can be hidden from you. Is that reasonable? To aim for just having it have read access?

**Comment by yangl900** [comment]
Probably need understand more about self-labeling, can master do that instead? from my own testing, if I remote the SPN it doesn't seem have a functionality impact.

MSI could be much better, and I think kubelet should not assume the MSI has permission to read the node itself from control plane. if it lacks such permission, it's probably not the end of the world. we should let everything else continue work. thoughts?

**Comment by colemickens** [comment]
Your other issue, about labeling with the SKU... if you had a SPN and the cloud-provider/config on, then your nodes would've have gotten region/sku/fault-domain labels automatically.

>MSI could be much better, and I think kubelet should not assume the MSI has permission to read the node itself from control plane.

Well, in the case of MSI, we could choose to give it just read-only permissions. I guess users could modify the template to remove it if they wanted, but I think this is behavior we want to have.

Long term, these things are going to go away due to much needed features in Azure lighting up - we're going to get tokens from IMDS eventually, identity from IMDS, and we won't need to do any SPN stuff at all really. Additionally, eventually "cloudprovider" integration in Kubernetes will be run as separate addons that you might be able to more easily opt-in/out of.

**Comment by anhowe** [comment]
We should add to the model to disable the SPN on the agents.  We can warn to the customers that it will break their labels.  This may be ok if the customer can alternatively add labels per #139

**Comment by xied75** [comment]
Hi guys, please advise if this could be any potential security issues? I just spin up an ACS K8 cluster on my Azure account, would this SPN thing bring any risk to my account in any way?

**Comment by colemickens** [comment]
It's a service account just like are used on other clouds. There is a difference in the danger posed in the crendentials are exfiltrated though... AWS and GCE just give out a short-lived token, whereas we are putting `client_secret` into the VM.

I'm trying to push for Azure to provide the equivalent functionality so that we can use it and get out of handling ServicePrincipals directly.

**Comment by anhowe** [comment]
Once we add labels, we can remove kubelet from talking to ARM.  We have noticed that scaling tests failed because all the kubelet calls resulted in throttling.

**Comment by colemickens** [comment]
If we do so, it should be temporary until we have the metadata service where we can get this information into the cloudprovider. That avoids hard-coding labels on kubelet flags, and it avoids quota problems.

Consider resizing a node for example .... the label(s) will end up being incorrect.

**Comment by colemickens** [comment]
Actually, @anhowe , if we do this, we break any FD support we have today in the scheduler. I strongly suggest that we not do this and document it as a workaround until IMDS is ready.
