### ISSUE TITLE
Add subnets to Route Table in Custom VNet context

### ISSUE THREAD

**Issue by sylr** [Azure/acs-engine#1902]
**Is this a request for help?**: NO 

---

**Is this an ISSUE or FEATURE REQUEST?**:  FEATURE REQUEST

---

**What version of acs-engine?**: HEAD

---

When using custom VNET we need to manually add the subnets to the Route table. It would be nice if it were to be done automatically.

Cheers.

**Comment by jackfrancis** [comment]
@sylr We're in the process of shifting over from kubenet network implementation to native Azure CNI implementation (it's in master right now). Here's an example api model that reflects how to build a cluster with bring your own VNET:

https://github.com/Azure/acs-engine/blob/master/examples/vnet/kubernetesvnet-azure-cni.json

The only difference between Azure CNI and kubenet from an api model configuration perspective is the `vnetCidr` property in `masterProfile`, which is meant to map to the useable IP address space in the VNET.

The reason all this info dump about Azure CNI! is because with Azure CNI-backed clusters, the custom VNET process no longer requires a manual route table attachment step.

Let me know if you have any questions!

**Comment by markgar** [comment]
Can we use Calico with Azure CNI?  Without some network policy, either from Calico or from Azure ASGs, to me, Azure CNI is a non-starter.

**Comment by hmarcelodn** [comment]
Yes, would be a nice feature. I automated the routing tables by script in my automation pipeline

**Comment by shueybubbles** [comment]
Is this supposed to be supported by acs-engine 0.11 already? I believe I've edited my json correctly to use my ExpressRoute subnet, but I get this error:
}\\r\\n}\"},{\"code\":\"BadRequest\",\"message\":\"{\\r\\n  \\\"error\\\": {\\r\\n    \\\"code\\\": \\\"SubnetIsFull\\\",\\r\\n    \\\"message\\\": \\\"Subnet 
/subscriptions/<subid>/resourceGroups/ERNetwork/providers/Microsoft.Network/virtualNetworks/SqlTools-CUS-CORP-USC-VNET-6882/subnets/Subnet-1 with address prefix 10.116.97.128/27 is already full.\\\",\\r\\n 

{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes"
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "",
      "vmSize": "Standard_D2_v2",
      "vnetSubnetId" : "/subscriptions/<subid>/resourceGroups/ERNetwork/providers/Microsoft.Network/virtualNetworks/SqlTools-CUS-CORP-USC-VNET-6882/subnets/Subnet-1",
      "firstConsecutiveStaticIP": "10.116.97.145",
      "vnetCidr" : "10.116.97.128/27"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D2_v2",
        "availabilityProfile": "AvailabilitySet",
        "vnetSubnetId": "/subscriptions/<subid>/resourceGroups/ERNetwork/providers/Microsoft.Network/virtualNetworks/SqlTools-CUS-CORP-USC-VNET-6882/subnets/Subnet-1"
      }
      
    ],
    "linuxProfile": {
      "adminUsername": "azureuser",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "<clientappidguid>",
      "secret": "<clientpwd>"
    }
  }
}

**Comment by jackfrancis** [comment]
@markgar @hmarcelodn Azure CNI for IPAM + Calico for network policy is not yet supported, though a native IPAM + network policy solution is in the roadmap.

@shueybubbles Azure CNI + bring your own VNET + a `/27` is not quite an edge case, but it's tricky because the current implementation isn't optimized for smaller networks. Although, you do only have one master, so I suggest you try this, if the cluster you built is disposable. Tear down your cluster, free up any lingering static IP addresses, and then choose a higher number for `firstConsecutiveStaticIP` (say, `10.116.97.157`).

@sharmasushant and the Azure CNI team are working on making this process better in practice, thanks for your patience!

**Comment by shueybubbles** [comment]
@jackfrancis your tip made me look more closely at azuredeploy.json. I ended up just deleting a bunch of the ipconfig# values for each VM so there are only 6 network interfaces on each, then manually deployed using the Azure cmdlet. It's up and running, I'll try to run my app later.
thanx

**Comment by jackfrancis** [comment]
Great! Please re-open if something fishy is up and watch this space for improvements in the process. :)
