### ISSUE TITLE
don't throw away error return values semver.NewVersion

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#1922]
In lots of places in code, we're currently throwing away the error result from invocations of `semver.NewVersion()`.

Acceptance criteria:

- all instances of `semver.NewVersion` should check the error response (2nd return value), and if non-nil, return it
- some functions that use `semver.NewVersion` will need to be refactored to return an error as an additional return value
- the invocation patterns against any refactored functions will also need to be refactored
- tests will need to be updated accordingly

**Comment by zqingqing1** [comment]
Hi @jackfrancis , checked with Jingtao @rjtsdl , we don't need to handle the error return of semver.NewVersion(), since it won't have any errors. The argument string in the semver.NewVersion(version string) is already validated in the Validate() function in the validate.go file under pkg/api/vlabs. As you see from the below codes, this is validation in the Validate() function. If the version is empty string(which means the Version is not in AllKurbenetesSupportedVersions map), then it will return error.
```
version := common.RationalizeReleaseAndVersion(
				o.OrchestratorType,
				o.OrchestratorRelease,
				o.OrchestratorVersion)
			if version == "" {
				return fmt.Errorf("OrchestratorProfile is not able to be rationalized, check supported Release or Version")
			}
``` 
How do you think? I think I don't need to implement it since it's already validated when creating the api.ContainerService.

**Comment by zqingqing1** [comment]
Checked with @rjtsdl and @dmitsh , there is one place needed to be handled error return.
