### ISSUE TITLE
acs-engine ARM Template is not working

### ISSUE THREAD

**Issue by hmarcelodn** [Azure/acs-engine#1937]
Hello,

I am trying to deploy an ARM Template already deployed with acs-engine and I got the following errors when I placed it into CI/CD.

> TemplateFailedPrevalidation: The template request has multiple validation failures involving one or more Microsoft.Network resources.

I am using acs-engine ARM Template generated after using deploy command. v0.5.0.

When I generated this with generate command its working.

Below it my cluster def:

```
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes"
      },
      "masterProfile": {
        "count": 1,
        "dnsPrefix": "edge-eastus2-development",
        "vmSize": "Standard_D2_v2",
        "vnetSubnetId": "/subscriptions/b458b57f-a2cb-485e-8f50-5efaef7968a3/resourceGroups/edge-cluster-resources/providers/Microsoft.Network/virtualNetworks/vnet_edge/subnets/kubernetes-nodes-subnet",
        "firstConsecutiveStaticIP": "10.0.5.5"     
      },
      "agentPoolProfiles": [
        {
          "name": "agentpool1",
          "count": 1,
          "vmSize": "Standard_D2_v2",
          "availabilityProfile": "AvailabilitySet",
          "vnetSubnetId": "/subscriptions/b458b57f-a2cb-485e-8f50-5efaef7968a3/resourceGroups/edge-cluster-resources/providers/Microsoft.Network/virtualNetworks/vnet_edge/subnets/kubernetes-nodes-subnet"             
        }
      ],
      "linuxProfile": {
        "adminUsername": "azureuser",
        "ssh": {
          "publicKeys": [
            {
              "keyData": ""
            }
          ]
        }
      },
      "servicePrincipalProfile": {
        "servicePrincipalClientID": "",
        "servicePrincipalClientSecret": ""
      }
    }
  }
```

I cannot re-generate since its a production cluster already working. I just need to have the ARM Templates automated. 

Thanks!

**Comment by jackfrancis** [comment]
Hi @hmarcelodn, what are you trying to do at a high level? Are you trying to build a new cluster using previously working api model configuration?

**Comment by hmarcelodn** [comment]
Hi @jackfrancis ,

I have my cluster generated with acs-engine deploy command. I would like to be able to reuse those ARM files generated in my automated pipeline so I can be able to perform an environment recreation in case of disaster recovery.

Tonight I generated my ARM templates with acs-engine generate command instead. I placed it in my pipeline and I was able to create the same cluster many times without any problem. 

So I said, "ok, i can take my current ARM templates and do exactly the same than my POC" but this error just appeared when runnung the deployment in "validation-only" approach. Just to highlight, all my ARM templates for all environment created thru the acs-engine deploy command failed in the same way.

Thanks!

**Comment by anhowe** [comment]
@hmarcelodn to see the errors, you can go to https://resources.azure.com, drill down to the resource group, expand "Microsoft.Resources" and look for the deployments with "x" character beside them, and it should show each error.

I took a look and saw the following errors for your deployment on Dec 15th:
1. Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 10
2. resourceGroups/edge-cluster-resources/providers/Microsoft.Network/networkInterfaces/k8s-agentpool1-37128902-nic-0 can only reference resouces in subscription(s) SUBID-REDACTED#1. Value /subscriptions/SUBID-REDACTED#2/resourceGroups/edge-cluster-eastus2/providers/Microsoft.Network/virtualNetworks/vnet-eastus2/subnets/k8s-nodes-subnet references wrong subscription.\"

For #2, you can only reference a VNET defined in the same subscription.

I'll close this issue for now, since the template was correct, but please re-open if you have more questions.
