### ISSUE TITLE
Error while scaling agent nodes

### ISSUE THREAD

**Issue by ashishkulk** [Azure/acs-engine#2035]
**Is this a request for help?**:
No
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
v0.14.5
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes 1.9.5

**What happened**:
There seems to be an issue with scaling the node. 

After running the following command to scale the availability set: 

```
acs-engine scale --subscription-id xxxx  --location australiasoutheast --resource-group test-cluster --node-pool dbpool1 --new-node-count 2 --deployment-dir ./_output/test-cluster/  --auth-method client_secret --client-id xxxx --client-secret xxxx --master-FQDN xxxx.australiasoutheast.cloudapp.azure.com
```

Error Received: 

```
INFO[0000] validating...
INFO[0004] Name suffix: 22165019
ERRO[0007] Failed to drain node k8s-dbpool1-22165019-2, got error No Auth Provider found for name "azure"
ERRO[0007] Got error Node 'k8s-dbpool1-22165019-2' failed to drain with error: 'No Auth Provider found for name "azure"', while draining the nodes to be deleted
Error: Node 'k8s-dbpool1-22165019-2' failed to drain with error: 'No Auth Provider found for name "azure"'
```

**What you expected to happen**:
Agent pool should scale accordingly.

**How to reproduce it** (as minimally and precisely as possible):
1) Install Kubernetes via ACS-Engine
2) Ensure to enable AAD integration
3) Run command to scale agent nodes

**Anything else we need to know**:
This cluster has AAD integration turned on, with managed disks and calico CNI is used.

Thanks in advance.

**Comment by alexquintero** [comment]
I have this same issue, but only when scaling down.

**Comment by ashishkulk** [comment]
I can correlate with @alexquintero . It only happens while scaling down the cluster.

```
INFO[0028] Name suffix: xxxxx
ERRO[0028] Failed to drain node k8s-agentpool1-xxxxx-4, got error No Auth Provider found for name "azure"
ERRO[0028] Got error Node "k8s-agentpool1-xxxxx-4" failed to drain with error: No Auth Provider found for name "azure", while draining the nodes to be deleted
Error: Node "k8s-agentpool1-xxxxx-4" failed to drain with error: No Auth Provider found for name "azure"

FATA[0028] Node "k8s-agentpool1-xxxxx-4" failed to drain with error: No Auth Provider found for name "azure"
```

**Comment by anujshankar** [comment]
I have this same issue, but only when scaling down.

**Comment by raycrawford** [comment]
I have this issue as well with 0.17.1.  Is there any update?  Thanks!

**Comment by stephenlawrence** [comment]
For scaling dow after a scale up this workaround worked for me:

The main issue was that after `acs-engine scale` failed to scale, and when I manually ran `kubectl delete node XXXX` acs-engine was still seeing my VM because it was not deleted from Azure and acs-engine it basically looking at the output from `az vm list --resource-group MyResourceGroup` which still showed 3 agentpool VM's.

This worked for me to scale back to 2 agentpool nodes after my scale up to 3:

1. `kubectl drain agentpool0-xxxxxx-2 --ignore-daemonsets`
2. `kubectl delete node agentpool0-xxxxxx-2`
2. Edited the apimodel.json file in the _output folder and set the current pool size back to 2
3. In Azure Portal, delete VM and NIC associated with the VM.
4. `acs-engine scale ...`

Hope that helps.
