### ISSUE TITLE
Cannot connect to Docker daemon

### ISSUE THREAD

**Issue by chlaterz** [Azure/acs-engine#2043]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

Unsure

**What happened**:
Trying to use Docker in an Azure Deep Learning VM.  No Docker commands are working.  The error message I get is:

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**How to reproduce it** (as minimally and precisely as possible):
Any Docker command will trigger the same, response; for example:
(sudo) docker ps

**Anything else we need to know**:
I tried starting the docker daemon manually, and no luck.  
Also, I was using the VM successfully in the past; one day I just started seeing this error message.

**Comment by andyzhangx** [comment]
could you run `sudo service docker start` and `sudo service docker status`?

**Comment by chlaterz** [comment]
Running the first comman gives the following:

$ sudo service docker start
Job for docker.service failed because the control process exited with error code. See "systemctl status docker.service" and "journalctl -xe" for details.

As suggested, I then tried the following (note, this gives the same results as ` sudo service docker status`):

$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: inactive (dead) (Result: exit-code) since Tue 2018-01-16 18:28:46 UTC; 2min 13s ago
     Docs: https://docs.docker.com
  Process: 28738 ExecStart=/usr/bin/dockerd -g /data/docker -H fd:// (code=exited, status=1/FAILURE)
 Main PID: 28738 (code=exited, status=1/FAILURE)

Jan 16 18:28:46 <vm_name> systemd[1]: Failed to start Docker Application Container Engine.
Jan 16 18:28:46 <vm_name> systemd[1]: docker.service: Unit entered failed state.
Jan 16 18:28:46 <vm_name> systemd[1]: docker.service: Failed with result 'exit-code'.
Jan 16 18:28:46 <vm_name> systemd[1]: docker.service: Service hold-off time over, scheduling restart.
Jan 16 18:28:46 <vm_name> systemd[1]: Stopped Docker Application Container Engine.
Jan 16 18:28:46 <vm_name> systemd[1]: docker.service: Start request repeated too quickly.
Jan 16 18:28:46 <vm_name> systemd[1]: Failed to start Docker Application Container Engine.
lines 1-14/14 (END)

**Comment by praveendhac** [comment]
I faced the same issue. Docker service is running but cannot run container. My output below.

[pdarshanam@pdarshanam-test-docker ~]$
[pdarshanam@pdarshanam-test-docker ~]$ date; echo -ne "\nRUN CONTAINER\n"; sudo docker run ubuntu; date; echo -ne "\nRUN SYSTEMCTL DOCKER STATUS\n"; sudo systemctl status docker.service; date; echo -ne "\nRunning OSCAP_DOCKER\n"; sudo oscap-docker image ubuntu; date; echo -ne "\nRunning SERVICE DOCKER STATUS\n"; sudo service docker status; date;
Wed  2 May 14:04:32 UTC 2018

RUN CONTAINER
/usr/bin/docker-current: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See '/usr/bin/docker-current run --help'.
Wed  2 May 14:04:32 UTC 2018

RUN SYSTEMCTL DOCKER STATUS
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-05-02 13:32:35 UTC; 31min ago
     Docs: http://docs.docker.com
 Main PID: 908 (dockerd-current)
   CGroup: /system.slice/docker.service
           ├─ 908 /usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=docker-runc --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current --sec...
           └─1077 /usr/bin/docker-containerd-current -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runti...

May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.182720579Z" level=debug msg="Registering GET, /networks"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.182785879Z" level=debug msg="Registering GET, /networks/"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.182864480Z" level=debug msg="Registering GET, /networks/{id:.+}"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.182950781Z" level=debug msg="Registering POST, /networks/create"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.183010581Z" level=debug msg="Registering POST, /networks/{id:.*}/connect"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.183130482Z" level=debug msg="Registering POST, /networks/{id:.*}/disconnect"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.183279983Z" level=debug msg="Registering POST, /networks/prune"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.183355583Z" level=debug msg="Registering DELETE, /networks/{id:.*}"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.194760763Z" level=info msg="API listen on 127.0.0.1:2376"
May 02 13:32:35 pdarshanam-test-docker systemd[1]: Started Docker Application Container Engine.
Wed  2 May 14:04:32 UTC 2018

Running OSCAP_DOCKER
The docker daemon does not appear to be running
Wed  2 May 14:04:32 UTC 2018

Running SERVICE DOCKER STATUS
Redirecting to /bin/systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2018-05-02 13:32:35 UTC; 31min ago
     Docs: http://docs.docker.com
 Main PID: 908 (dockerd-current)
   CGroup: /system.slice/docker.service
           ├─ 908 /usr/bin/dockerd-current --add-runtime docker-runc=/usr/libexec/docker/docker-runc-current --default-runtime=docker-runc --exec-opt native.cgroupdriver=systemd --userland-proxy-path=/usr/libexec/docker/docker-proxy-current --sec...
           └─1077 /usr/bin/docker-containerd-current -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runti...

May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.182720579Z" level=debug msg="Registering GET, /networks"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.182785879Z" level=debug msg="Registering GET, /networks/"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.182864480Z" level=debug msg="Registering GET, /networks/{id:.+}"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.182950781Z" level=debug msg="Registering POST, /networks/create"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.183010581Z" level=debug msg="Registering POST, /networks/{id:.*}/connect"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.183130482Z" level=debug msg="Registering POST, /networks/{id:.*}/disconnect"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.183279983Z" level=debug msg="Registering POST, /networks/prune"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.183355583Z" level=debug msg="Registering DELETE, /networks/{id:.*}"
May 02 13:32:35 pdarshanam-test-docker dockerd-current[908]: time="2018-05-02T13:32:35.194760763Z" level=info msg="API listen on 127.0.0.1:2376"
May 02 13:32:35 pdarshanam-test-docker systemd[1]: Started Docker Application Container Engine.
Wed  2 May 14:04:32 UTC 2018
[pdarshanam@pdarshanam-test-docker ~]$

**Comment by chaoshunh** [comment]
it is horrible. Azure data science VM
