### ISSUE TITLE
Faulty calculation based on firstConsecutiveStaticIP?

### ISSUE THREAD

**Issue by ITler** [Azure/acs-engine#2054]
**Is this a request for help?**:
think it is a bug. At least I didn't find documentation stating, that this is desired behavior :)
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
issue
---

**What version of acs-engine?**:
v0.10.0
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
k8s client: 1.9.1 server 1.8.4

**What happened**:
As I need to restrict IP ranges used for Kubernetes Cluster, I was playing around a bit with different configuration stumbling upon a strange thing.

I restrict my subnet to 172.29.2.0/23 with is same range as vnet and set firstConsecutiveStaticIP to 172.29.3.250, like that:
```
"masterProfile": {
      "count": 3,
      "dnsPrefix": "test",
      "vmSize": "${vm_size_master}",
      "vnetSubnetId": "${subnet_id}",
      "firstConsecutiveStaticIP": "172.29.3.250"
    },
```
During deployment an error was raised:
```
ERROR: Deployment failed. {
  "error": {
    "code": "InvalidPrivateIPAddressFormat",
    "message": "Private static IP address value 172.29.3.260 is invalid.",
    "details": []
  }
}
```

* NO, there is no typo in my deployment template :)
* This IP seems to be the one to be assigned the the **internal** k8s-master loadbalancer `k8s-master-internal-lb`
* When using `"firstConsecutiveStaticIP": "172.29.3.240"` as a work-around, everything works fine, obviously. 

For me it is not an urgent issue, but maybe it is worth knowing about and fixing it anyway.

**What you expected to happen**:
No calculation error

**Comment by tamilmani1989** [comment]
@ITler Can you please share your cluster config?

**Comment by ITler** [comment]
Sure

```
{
  "apiVersion": "vlabs",
  "location": "germanycentral",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorRelease": "1.8",
      "orchestratorVersion": "1.8.4"
    },
    "masterProfile": {
      "count": 3,
      "dnsPrefix": "demo",
      "vmSize": "Standard_A2",
      "vnetSubnetId": "${subnet_id}",
      "firstConsecutiveStaticIP": "172.29.3.250"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 1,
        "vmSize": "Standard_A2m_v2",
        "vnetSubnetId": "${subnet_id}",
		"storageProfile" : "ManagedDisks",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "${admin_user}",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "${ssh_pkey}"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientID": "${service_principle_client_id}",
      "secret": "${service_principle_client_secret}"
    }
  }
}

```

**Comment by tamilmani1989** [comment]
Thank you for letting us know. We will let you know if we fix this

**Comment by mcwienczek** [comment]
I am having similar issue. Can someone explain why is this happening?

**Comment by stremmie** [comment]
I happen to have been looking into how the parameter 'firstConsecutiveStaticIP' is being used in azuredeploy.json.  It is used to create the private IP addresses of the masters.  E.g. if 'firstConsecutiveStaticIP' is 172.29.3.250 and there will be 3 masters then they will assigned 172. .29.3.250, 172.29.3.251 and 172.29.3.252.  the problem is that the IP address for the APIServer IP is calculated as follows:
"kubernetesAPIServerIP": "[concat(variables('masterFirstAddrPrefix'), add(variables('masterInternalLbIPOffset'), int(variables('masterFirstAddrOctet4'))))]",
Where masterFirstAddrPrefix is the first3 octets of  'firstConsecutiveStaticIP', 'masterInternalLbIPOffset' has a constant value 10 and masterFirstAddrOctet4 is the last octet of 'firstConsecutiveStaticIP'.

Putting that together gives a APIServer IP of **172.29.3.260** which is an illegal IP address. The error that ITler is therefore as expected based on the azure template that acs-engine produces.

I am just starting with ACS-Engine myself and would appreciate better documentation.  ACS-Engine gives me a 'firstConsecutiveStaticIP' default of 10.0.9.5 which will always fail when creating three NICs due to the overlapping private IP addresses that are reserved.  I have now set it to 10.0.9.150 to avoid that problem.

(My observations where based on on ACS-engine 0.12.5 with Kubernnetes 1.7.9)

**Comment by tamilmani1989** [comment]
_<"Putting that together gives a APIServer IP of 172.29.3.260 which is an illegal IP address. The error that ITler is therefore as expected based on the azure template that acs-engine produces.">_

You are correct. We have to change this behavior. Instead of blindly adding to last octet, we need to convert to integer and add lboffset.
_<"I am just starting with ACS-Engine myself and would appreciate better documentation. ACS-Engine gives me a 'firstConsecutiveStaticIP' default of 10.0.9.5 which will always fail when creating three NICs due to the overlapping private IP addresses that are reserved. I have now set it to 10.0.9.150 to avoid that problem.">_

 This issue was fixed already with this PR -> [https://github.com/Azure/acs-engine/pull/1966](url).  acs-engine 0.13.0 has this fix.

**Comment by ITler** [comment]
>ACS-Engine gives me a 'firstConsecutiveStaticIP' default of 10.0.9.5 which will always fail when creating three NICs due to the overlapping private IP addresses that are reserved. 

I also faced issue when using IPs with lower range D value, i.e. 172.29.3.`10` ... If remembering correctly, masters' IPs interfere with either each other or with agents' IPs. That's why, I went up to *firstConsecutiveStaticIP* = 172.29.3.240
