### ISSUE TITLE
SwarmMode shows agents as "down"

### ISSUE THREAD

**Issue by rgardler** [Azure/acs-engine#215]
I deployed a Swarm Mode cluster with two agents. When I do `docker node ls` I get:

```
ID                           HOSTNAME                     STATUS  AVAILABILITY  MANAGER STATUS
hckh3be59qj45k8dpcrrpibyy *  swarm-master-75773396-0      Ready   Pause         Leader
jhhsx11wymnhugckdsvilcw8p    swarm-public-75773396000001  Ready   Active
rqtoizc7of1hqv1d2tm7430ms    swarm-public-75773396000002  Down    Active
uwofxnqb9056a7iws58qjat5u    swarm-public-75773396000000  Ready   Active
```

I assume that the third worker was a result of overprovisioning and was removed after it had registered with the cluster. 

Is there any way we can clean up after initialization?

/cc @amanohar

**Comment by anhowe** [comment]
some possible workarounds:
1. determine if there is a timeout for expiring old nodes, and submit a bug to docker if there isn't.  They should build for a cloud where VMs are dynamic
2. not great, but potentially adding a 60s sleep before registering
3. we can disable overprovisioning

**Comment by rgardler** [comment]
-1 on disabling overprovisioning unless there is some mechanism to ensure the right number of agents is brought up.

I'm assuming #2 would result in a 60s increase in overall deployment time. I'm not keen on this.

Lets explore #1 at an appropriate time (I think we can live with this for a period)

**Comment by amanohar** [comment]
We shouldn't try to clean up after initialization in this case at least unless we know of way to determine if the node was down due to overprovisioning or if the node was down for another (unexpected) reason.

@rgardler, when you say clean up after initialization you mean that Swarm shouldn't show those down nodes at all? 

I am not keen on #2 either as it adds to overall deployment time and is not deterministic. I have seen VMSS take more than 60s sometimes to remove overprovisioned nodes.

**Comment by rgardler** [comment]
If I ask for 2 workers and have 2 healthy and 1 unhealthy then it’s a good assumption that it’s overprovisioning. Even if it’s not I don’t care about a VM that I didn’t ask for not being active. I should never see it as “down”.

Ross

**Comment by amanohar** [comment]
Swarm Mode does something similar in case of scale down as well. If you scale down, it still show the node with status as 'Down' and availability as 'Active' which seems incorrect/confusing. 

I will leave my cluster running the whole day today and see if it removes the node at some point. I have tried it for 30 mins and it didn't seem to be remove the node. If it doesn't remove the node we can follow up with Docker.

**Comment by amanohar** [comment]
Update: I had a cluster with 3 agent nodes. I scaled down to 2 and left the cluster running for 5+ hours. Swarm Mode still show the deleted node when doing "docker node ls" with status = down, availability = active. 

I will follow up with Docker on this.

**Comment by anhowe** [comment]
Dropping to P2, since it is not clear that the downed node is causing scheduling issues and more a display issue from the CLI point of view.  If this is causing scheduling issues, let's raise back to P1.

**Comment by anhowe** [comment]
This also affects scale-down.  This is not great UI wise, however, this is an upstream issue, and does not affect scheduling of containers.

Please re-open if this causes container scheduling issues.

**Comment by artisticcheese** [comment]
Can somebody explain to me how scaling up/down and reimaging of the the VM scale sets reflects on swarm nodes. I can see that provisioning script for hybrid Windows container deployment in ACS have all the neccessary plumbing for adding nodes to swarm. But what happens when you reimage for example individual VM scale set machine, or you can scale up and then scale down worker nodes. There is no clean up script provided anywhere. Does it mean that swarm will end up with dead members forever?
