### ISSUE TITLE
Re-generating deployment files from existing cluster

### ISSUE THREAD

**Issue by abelsromero** [Azure/acs-engine#2250]
**Is this a request for help?**:

Yes

**What version of acs-engine?**:

0.4.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kuberntes 1.6.6

**What happened**:

Deployment files generated are not available and need to re-scale cluster.

**What you expected to happen**:

There is a way to generate the deployment files required to keep working with the current clusters.

**Comment by JunSun17** [comment]
Can you use "acs-engine scale" command to re-scale your cluster?

**Comment by JunSun17** [comment]
Sorry, I think I misunderstand your question. If you mean the original deployment files in _output folder is gone, right now we do not have a way to regenerate it.

**Comment by abelsromero** [comment]
So, I undertand the only option is to create a new cluste from scratch then.
No issue with that, our fault :laughing: , just want to be 100% sure.

**Comment by kiddouk** [comment]
I am myself in the process of having to do the exact same. Mostly because we inherit from a cluster created by `az acs`. So far, this is rather painful. anyone has any good advice on the necessary steps?

So far I see the following:
1) re create the cluster definition out of `az acs show`
2) connect on the master node and retrieve the apiServerkeys, root ca and client certs
3) run acs-engine generate on the cluster definition
3) replace the generated keys, certs and ca by the one retrieved both in files and templates.

Anything that is missing?

**Comment by abelsromero** [comment]
We tried generating from the deployment files from Azure Portal but we were not able to get it working.
So, we ended up creating a new cluster. We struggled a bit to be able to connect to to the same vnet, but we got it running now.
If you succed, first, _kudos to you! _, then please do share it to help others.
