### ISSUE TITLE
Audit policy not working

### ISSUE THREAD

**Issue by JunSun17** [Azure/acs-engine#2312]
**Is this a request for help?**:

No

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

Issue

**What version of acs-engine?**:

v0.13.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

Error is reported in kubelet log:

Feb 20 07:22:25 k8s-master-27067430-2 docker[1838]: E0220 07:22:25.311339    1913 file.go:149] Can't process manifest file "/etc/kubernetes/manifests/audit-policy.yaml": /etc/kubernetes/manifests/audit-policy.yaml: couldn't parse as pod(no kind "Policy" is registered for version "audit.k8s.io/v1beta1"), please check manifest file.

**What you expected to happen**:

audit-policy.yaml is processed correctly.

**Comment by pidah** [comment]
@JunSun17 what version of kubernetes is this ?

**Comment by JunSun17** [comment]
@pidah The one I tested is version 1.8.6.

**Comment by pidah** [comment]
@jackfrancis @JunSun17  Just had a quick look https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/config/file.go#L196
I think the problem is the location of the file; all files in /etc/kubernetes/manifests/ are supposed to be pods it seems and kubelet couldn't parse the audit policy file as its not a pod manifest. I think moving the audit policy to a different location ( or making it a hidden file which kubelet should ignore https://github.com/kubernetes/kubernetes/blob/master/cmd/kubelet/app/options/options.go#L448 ,but not recommending )  would stop the error.
However, the audit policy is being applied by the API server and not affected by this.

**Comment by maniSbindra** [comment]
@jackfrancis which path would you suggest moving the audit-policy.yaml file to? 
* to /etc/kubernetes/audit-policy.yaml
* or to /etc/kubernetes/audit-policy/audit-policy.yaml
* or any place else

**Comment by jackfrancis** [comment]
@maniSbindra I would try `/etc/kubernetes/addons` Thanks! Let me know if that (plus the kube-addon-manager picking up the change) removes the error message and starts applying the policy.
