### ISSUE TITLE
masterEndpointDNSNamePrefix hard coded inside azuredeploy.json after generating templates

### ISSUE THREAD

**Issue by maxhov** [Azure/acs-engine#2347]
**Is this a request for help?**:
---
Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
---
Issue / Feature somewhere inbetween

**What version of acs-engine?**:
---
0.13.0

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
In the resulting Azure Resource Manager template, generated by acs-engine, the name of the cluster is hardcoded inside the ARM template in the '--cluster-name' argument within the osProfile.customData of the master vm profile (don't know which binary it is an argument of).

**What you expected to happen**:
The '--cluster-name' argument is referenced as a parameter/variable within the ARM template. Currently, the 'masterEndpointDNSNamePrefix' is used for the cluster name. I would suggest referencing the parameter instead of hard coding the value.

Not hard coding the cluster name inside the azuredeploy.json. This allows for changes on deployment time without the need to change values inside the azuredeploy.json.

**How to reproduce it** (as minimally and precisely as possible):
Search for '--cluster-name' inside the generate azuredeploy.json ARM template that was generated with the following apimodel:
`
{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.9.3",
      "kubernetesConfig": {
        "networkPolicy": "calico",
        "enableDataEncryptionAtRest": true,
        "enablePodSecurityPolicy": true,
        "enableRbac": true,
        "maxPods": 300,
        "useInstanceMetadata": false,
        "addons": [
            {
              "name": "tiller",
              "enabled" : false
            },
            {
              "name": "kubernetes-dashboard",
              "enabled" : true
            },
            {
              "name": "rescheduler",
              "enabled": false
            },
            {
              "name": "aci-connector",
              "enabled": false
            }
        ]
      }
    },
    "masterProfile": {
      "count": 1,
      "dnsPrefix": "dnsprefix",
      "vmSize": "Standard_D4_v3",
      "osDiskSizeGB": 40,
      "storageProfile": "ManagedDisks"
    },
    "agentPoolProfiles": [
      {
        "name": "agentpool1",
        "count": 2,
        "vmSize": "Standard_D4_v3",
        "osType": "Linux",
        "availabilityProfile": "AvailabilitySet",
        "storageProfile": "ManagedDisks"
      }
    ],
    "linuxProfile": {
      "adminUsername": "user",
      "ssh": {
        "publicKeys": [
          {
            "keyData": "<CHANGE>"
          }
        ]
      }
    },
    "servicePrincipalProfile": {
      "clientId": "<CHANGE>",
      "secret": "<CHANGE>"
    }
  }
}
`

**Anything else we need to know**:
No

**Comment by JunSun17** [comment]
@0x6d6178 I checked a case and do not see the problem you mentioned. In my case, the --cluster-name is set to be the "dnsPrefix" in "masterProfile". Can you change this field in your model and regenerate/check the new azuredeploy.json?

**Comment by 0x6d6178** [comment]
@JunSun17 Thanks for getting back. Indeed, the dnsPrefix is used in the --cluster-name, but the value is hard coded. This means that for every change of the dnsPrefix, the complete ARM template needs to be regenerated via acs-engine. Wouldn't it be better to reference the value of the dnsPrefix in the --cluster-name argument with a parameter/variable?

**Comment by JunSun17** [comment]
@0x6d6178 I guess what you said probably can be done but is not a priority for acs-engine. The goal of acs-engine is to provide a tool that generate ARM templates based on user's cluster definition. Users can choose to directly adjust the generated ARM templates and apply their logic, but I guess it should not be the intended way to use acs-engine.

**Comment by 0x6d6178** [comment]
I understand what you are saying. However, I think it is strange that for some acs-engine cluster definition parameters, the resulting ARM template refers to them via the azuredeploy.parameters.json file and that other cluster definition parameters are being hard coded inside the azuredeply.json. This inconsistency makes debugging hard and reusability of the generated ARM templates low.

**Comment by JunSun17** [comment]
I did a search and "dnsPrefix" also shows up in apimodel.json, which will be used for upgrade and scale operations. So it looks to me it does not help much to parameterize "dnsPrefix" since it will cause in-consistency between apimodel.json and azuredeply.json. Basically it is not a parameter for tuning. If you really want to give it a try, you can manually change them to a desired value and see if it will work. No guarantees though.

**Comment by 0x6d6178** [comment]
I tried and it works. It is possible to change the hard coded value within the azuredeploy.json with a parameter (parameters() function) or variable (variables() function). Instead of hard coding the value of the cluster name inside the ARM template, parametrising it allows better re-use of the template as only one dnsprefix can be used at a time.

**Comment by 0x6d6178** [comment]
Any updates on this? Also noticed that the 'serverAppId' and 'clientAppId' are hard coded into the azuredeploy.json file that results from acs-engine. It would be nice if all Kubernetes configuration parameters in the apimodel.json are exposed via the azuredeploy.parameters.json file, instead of being hard coded into the azuredeploy.json file.

**Comment by JunSun17** [comment]
@0x6d6178 As I mentioned above, "dnsPrefix" is also used in apimodel.json.

When you do the initial deployment, you only need azuredeply.json (+parameters file). But when you do upgrade or scaling, you will need both apimodel.json and azuredeply.json, and "dnsPrefix" needs to be the same in both files for the operation to work.

That is my guess why "dnsPrefix" is not parameterized but instead hard coded, because parameterize it does not change the value in apimodel.json and may cause in-consistency. :)
