### ISSUE TITLE
running apt-get upgrade breaks cluster when using 0.13.0 

### ISSUE THREAD

**Issue by marty2bell** [Azure/acs-engine#2382]
**Is this a request for help?**: YES

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): ISSUE

---

**What version of acs-engine?**: 0.13.0

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

Kubernetes

**What happened**:

Deployed new cluster using the 0.13.0 engine, as part of the housekeeping, ran a sudo apt-get update followed by upgrade on the master node at which point running kubectl (anything) just hangs.

I confirmed kubectl was OK before patching the linux vm as this is the second cluster I have killed by doing this.

**What you expected to happen**:

Not to wreck the cluster!

**How to reproduce it** (as minimally and precisely as possible):

Exactly as above, just patch the vm and it should be useless.

**Anything else we need to know**:

**Comment by jackfrancis** [comment]
Hi @marty2bell we identified a regression in v0.13.0 (and released v0.13.1 w/ the fix) that didn't startup etcd on restart. Is this the root cause? If so, you can do one of the following:

1) build a new cluster (if that's an option) w/ v0.13.1
2) patch the existing cluster by running `sudo systemctl enable etcd` on all master and agent nodes

**Comment by marty2bell** [comment]
That's great thanks.  I'll patch for now and upgrade the engine for new builds.....

Cheers

Marty
