### ISSUE TITLE
Is production ready?

### ISSUE THREAD

**Issue by robsonpeixoto** [Azure/acs-engine#2422]
It the ACS-ENGINE production ready?
How are using?
What's the recommended Kubernetes version?

Thanks

**Comment by jackfrancis** [comment]
Hi @robsonpeixoto. acs-engine can build a variety of Kubernetes clusters on Azure. Depending on which Kubernetes runtime configuration and version each customer defines as "production ready" will answer your question! We currently support the most recently published patch release of 1.7 (`v1.7.13`), 1.8 (`v1.8.8`), and 1.9 (`v1.9.3`) (and soon 1.10).

Speaking very generally I'd recommend 1.8.8 at this time. I would *not* recommend a 1.9 release as there are known bugs across all cloud providers (Google, AWS, and Azure, etc) that will be fixed in `v1.9.4` (not yet published).

I hope this doc is sufficient to get you started!:

https://github.com/Azure/acs-engine/blob/master/docs/kubernetes/deploy.md#acs-engine-the-long-way

**Comment by robsonpeixoto** [comment]
"production ready" IMHO is:

- stable
- easy to update
- update without downtime
- easy to add/remove node pool
- good and stable PV and PVC
- good authorization/authentication support
- ingress or internal load balancer working well

Are there big players using acs-engine?

**Comment by hmarcelodn** [comment]
@robsonpeixoto we have a large application ready in production. We started from acs-engine 0.5.0 using k8s 1.6.6. It worked fine so far and you got lot of customization like custom vnet, number of master nodes. I had issues upgrading and scaling so far, so we usually works on a labs environment for testing new versions and if it worked we move ahead.

**Comment by oivindoh** [comment]
1.9.4 is finally out now, so just missing in acs-engine.

Unfortunately for those of us using azuredisk PVs, https://github.com/kubernetes/kubernetes/pull/60183 doesn't appear to have made it into the release (present in 1.8.9 though)

**Comment by patrick-motard** [comment]
@robsonpeixoto , I can share with you my teams experience so far.

My team is using 1.8.4 right now. We are doing a proof of concept with a multi-container application (4 windows containers, 1 linux). We are using a hybrid cluster.

We have run into a few roadblocks that if we can't solve, we won't be able to continue with acs-engine, and potentially kubernetes.

acs-engine 0.13.0 & k8s v1.8.4:

1. windows containers cannot resolve vnet level dns
2. windows containers dns resolution is inconsistent
3. hybrid clusters cannot target an existing vnet
4. horizontal pod scaling for windows containers isn't working
5. windows nodes system statistics aren't showing up in the dashboard
6. no element in the dashboard ui shows usage statistics for windows containers

Plus there is the list of know issues and limitations for windows containers found [here](https://kubernetes.io/docs/getting-started-guides/windows/). Some of the things in that list I linked I also tested out and confirmed (mentioned above), others we haven't tested yet.

I cannot speak to the stability of linux containers in the acs-engine, nor a pure linux cluster.

**Comment by ITler** [comment]
If you go to an Azure Custom Cloud (like AzureGermanCloud), I would recommend a lot of testing and having clusters run for a long time before relying for production use-case. We have serious problems, which we often can't explain as we didn't see them on other cloud providers. However, from our perspective it is often hard to say, if the issues come from acs-engine, kubernetes, the AzureGermanCloud implementation or a mix of all. Only few of these issues were solved by issue support here.
Nevertheless, I'm absolutely sure, that every contributor does the best he or she can do. But don't forget, that this is an open-source tool and it seems, it could need more man-power especially from MS side, but this might be a strategic/political question.

**Comment by jackfrancis** [comment]
Thanks everyone for all the thoughts here. To address @robsonpeixoto's line items:

- stable
  - acs-engine itself is both stable (certain tried-and-true cluster configurations will deploy successfully consistently) and unstable (by design acs-engine encourages experimentation and tinkering, so there is plenty of edge-case surface area, especially when using the bits that are nearest HEAD for Kubernetes itself [versions, API features])
  - Kubernetes itself is also not a monolith, and can be operated both stably and unstably. acs-engine is not designed to address this (i.e., to act as a convenience layer between the developer/operator and the k8s API): stability in the Kubernetes ecosystem is largely a function of experience with its API and managing distributed systems generally
- easy to update
  - acs-engine is not at this time consistently easy to update. This is primarily due to its heritage as an open, ad hoc designed tool to build a bunch of different container orchestrator systems ("bunch of" being a moving target over time). However, it is trending in the right direction. Internally, we are continually adding more test coverage to ensure that the things we care about the most (e.g., "deploy known working Kubernetes clusters") stay stable from release to release.
  - Kubernetes itself is not "easy" to update, though it provides a platform (consistent API is a key piece) for building redundant implementations on top of. There is an ecosystem of tooling consistently cropping up to help maintain Kubernetes, which is (1) a reflection of its success as a componentized system that is able to be complemented with tools and (2) a suggestion that "Kubernetes" is not a magic bullet that solves all your problems. A long-running Kubernetes environment will require tooling and expertise built around the ephemeral instances of particular APIs (i.e., Kubernetes clusters) to ensure stability over time. 
- update without downtime
  - acs-engine is designed to address this (cluster updates go one node at a time, cordon-and-drain workloads, and abort aggressively at first error). The downside to this approach is that error end states are manifold, and not all cluster end states are accounted for with acs-engine itself. So a cluster upgrade may leave your cluster itself in a state that requires manual intervention in order to, say, perform a follow-up upgrade using acs-engine. This is not ideal, but acs-engine is at its core not a cluster state management tool, but rather a cluster deployment tool. Managing cluster states reliably is better addressed with service-based solutions like AKS (public preview) or GKE.
- easy to add/remove node pool
  - "easy" is an opinion, but for most definitions it is probably not "easy" to do so
- good and stable PV and PVC
  - This is a Kubernetes concern and not acs-engine, really. acs-engine is designed to evolve w/ Kubernetes, so depending on your opinion of what is a "good and stable PV and PVC" impelmentation in Kubernetes, acs-engine either (1) supports it or (2) will support it with a working, well-tested PR.
- good authorization/authentication support
  - "good" is a moving target, but customers are using acs-engine w/ RBAC and AAD. Setting it up is not automatic.
- ingress or internal load balancer working well
  - There exist well-tested Kubernetes ingress and ILB options in acs-engine. As designed, acs-engine is flexible and so you are allowed to produce a Kubernetes cluster that has a poorly configured or experimental/non-working network stack.

Hope that speaks to some of the reality in this space!
