### ISSUE TITLE
How to benefit from a newer version of acs-engine on an existing cluster?

### ISSUE THREAD

**Issue by mrdfuse** [Azure/acs-engine#2475]
**Is this a request for help?**:

Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

QUESTION

**What version of acs-engine?**:

0.13.1

I'm sorry if this is not the right place but I don't find any other place to ask questions:
I have a cluster running created with acs-engine version 0.13.1. I noticed a newer version of acs-engine is now available, with a lot of bugfixes in it. How can I benefit from those bugfixes on my existing cluster, or is that not possible?  Or is it the same process as acs-engine upgrade?

**Comment by jackfrancis** [comment]
Hi @mrdfuse,

There are two types of bugfixes that you'll see in acs-engine as releases progress forward (e.g., from `v0.13.1` to `v0.14.0`:

1. improvements to reliability of cluster deployments, especially improving the breadth of the "types" of cluster configurations that are able to be reliably deployed
2. absorption of upstream Kubernetes fixes, especially w/ respect to the availability of newly released versions of Kubernetes

With respect to the 1st type, a new version of acs-engine does not add any value to your existing cluster (because it has already been deployed, and is running!).

With respect to the 2nd type, newer versions acs-engine *may* be able to move your cluster forward onto a newer version of Kubernetes, which could bring stability if the newer version of k8s includes fixes to behaviors that your workloads encounter.

`acs-engine upgrade`, unfortunately, is an alpha-ish feature at this point in terms of reliably enforcing cluster end state. We're working on publishing a whitelist of cluster configurations that upgrade works reliably against, but the nature of acs-engine generated clusters is that they tend to be distinct from one another (one of the chief purposes of acs-engine is to enable customization). Depending on how mission-critical your cluster is, you could do one of the following:

1. If your cluster is not mission critical, you could attempt an `acs-engine upgrade` against it using a newer version of acs-engine, knowing that (1) you may have to retry a few times to reach the desired cluster end state; and (2) there is the possibility that your cluster will be put into a state that is no longer "maintainable" by acs-engine
2. If your cluster is mission critical, I would recommend at the very least building another cluster with the same configuration, and then performing `acs-engine upgrade` against it using a newer version of acs-engine to analyze the compatilibity of your cluster w/ the current state of `acs-engine upgrade`. And then do that a few more times to get some real data about what this operation is likely to do to your production cluster. Finally, you could build a new cluster w/ a newer version of acs-engine, and then migrate your workloads to your new cluster, retiring the old one.

I hope that provides some realistic guidance!

**Comment by mrdfuse** [comment]
@jackfrancis totally clear, thanks so much for the detailed explanation!!
