### ISSUE TITLE
API model for "azure context"

### ISSUE THREAD

**Issue by jim-minter** [Azure/acs-engine#2540]
It would be useful to have a single standard place in the acs-engine API model to contain the cluster "azure context" (e.g. tenant id, subscription id, resource group and location).

Having these values defined up front includes the following advantages:
- these data can be statically templated into cluster configuration files, e.g. azure.conf, up front on the client side rather than as a dynamic server-side script
- strengthened data model with all input data in one place rather than some pieces learned ad-hoc during ARM template execution
- improved testability

Proposal:

```golang
# pkg/api/vlabs/types.go

// Properties represents the ACS cluster definition
type Properties struct {
	// ...
	AzProfile AzProfile `json:"azProfile,omitempty"` // new field added to struct
}

// AzProfile holds the azure context for where the cluster resides
type AzProfile struct {
	TenantID       string `json:"tenantId,omitempty"`
	SubscriptionID string `json:"subscriptionId,omitempty"`
	ResourceGroup  string `json:"resourceGroup,omitempty"`
	Location       string `json:"location,omitempty"`
}
```

Today some acs-engine sub-commands allow command-line arguments such as --subscription-id, --resource-group, --location to be specified.  It's proposed that these command-line arguments would override fields in the AzProfile of an input model.  The command-line arguments could optionally be extended to add --tenant-id, and/or the tenant id could be defaulted based on the discovered tenant when acs-engine connects to azure.

After adding the AzProfile struct, existing implementations which currently discover these values dynamically in the execution of the ARM template should consider moving to using the preconfigured values.

**Comment by jim-minter** [comment]
@jackfrancis @pweil- @kargakis ptal

**Comment by khenidak** [comment]
I understand why we need this in the model. I'm however concerned with:
1. Asking the user to provide an information we get from somewhere else (Arm template?). I think today we drive these as env vars into a custom script extension. 
2. Handling the cases where the user provide `resource-group:Gx location:Lx` and during deploy he deploy to `resource-group:Gy location:Ly`

**Comment by jackfrancis** [comment]
Thanks @jim-minter for scaffolding this design proposal. My thoughts:

- Basic interface spec proposal (novel struct under `Properties`) looks good
- roger on your defined order of configuration precedence:
  1. CLI context args
  2. api model
  3. inherited code-enforced defaults (probably not applicable for these properties in particular as they are all context-hungry)
- We want to ensure that the rationalization of `AzProfile` during template processing is implemented in such a way that is clearly context-aware. In other words, workflows that consume these novel configuration properties for the purpose of, say, delivering config along an alternate, non-CSE path, should be easily traceable/maintainable as separate workflow paths. No strong opinions about separate files/packages, just that the code implementation should be expressive so that we can confidently maintain multiple input/output pathways.

@khenidak Thanks for your thoughts. @CecileRobertMichon @seanknox @amanohar @slack FYI for any additional thoughts

**Comment by jim-minter** [comment]
> We want to ensure that the rationalization of `AzProfile` during template processing is implemented in such a way that is clearly context-aware. In other words, workflows that consume these novel configuration properties for the purpose of, say, delivering config along an alternate, non-CSE path, should be easily traceable/maintainable as separate workflow paths. No strong opinions about separate files/packages, just that the code implementation should be expressive so that we can confidently maintain multiple input/output pathways.

@jackfrancis I don't understand what you mean by this point.

**Comment by jackfrancis** [comment]
Sorry for the densely packed ambiguousness. :) Let's just call it an implementation detail that we'll iterate over as we move this forward. Not saying much there other than: let's make a clean implementation where intent is clear (i.e., "I'm code that is operable only when I have explicit access to an az context!" or "I'm code that doesn't need az context because ARM takes care of all that for me!").

The code as-is is already tricky, so we're inheriting some debt, we won't be unreasonable!
