### ISSUE TITLE
Can I configure master and agent DNS via acs-engine?

### ISSUE THREAD

**Issue by markwragg** [Azure/acs-engine#2631]
Hi,

I am using ACS engine to create a Kubernetes cluster which then pulls a container image from a private Artifactory repository. The address of the repository only resolves internally (it is not in public DNS). I have got it to successfully work by SSH'ing to the Master and Agent servers and configure the /etc/hosts file with the address of the repository, but obviously I don't want to have to make this manual change when this is in production. 

Can anyone advise me if there is any way to configure the DNS of the master/agent servers via ACS Engine during deployment, or what the right approach might be for configuring DNS so that I can resolve internal addresses from these servers? I am deploying in to a custom VNET.

I can't use the IP address as then I think certification verification fails (as its HTTPS), unless there might be some way to disable cert verification (although thats obviously not preferred).

Many Thanks,
Mark

**Comment by markwragg** [comment]
I'm coming to the conclusion that maybe the VNET i'm deploying in to should be configured to use the DNS servers deployed within that VNET that can then resolve internal DNS names, but i'm still interested to know if there are any alternative solutions to this.

**Comment by khaldoune** [comment]
@markwragg 
I've faced the same situation with custom DNS. Of corse you should declare it in your VNET but you still declare the VMs in that DNS.

In order to do that, you can do things like that the API model that you can find in the issue #2607.

The source code is here: 
[(https://gitlab.com/octo-carrefour-k8s/acs-extensions/raw/master/extensions/setup/v1/setup.sh](https://gitlab.com/octo-carrefour-k8s/acs-extensions/raw/master/extensions/setup/v1/setup.sh)

Please notice that this source should be available in an http server that your VMs can access during provisioning.

@jackfrancis 

Maybe could we make the documentation clear about the custom DNS and how the extensions work.
