### ISSUE TITLE
Remove deprecated Accelerators feature gateway for k8s

### ISSUE THREAD

**Issue by karataliu** [Azure/acs-engine#2790]
A deployment of 1.11.0-alpha.1 would fail to start kubelet on agent

```
Apr 27 03:06:45 k8s-agentpool1-40525011-0 kubelet[3422]: F0427 03:06:45.903754    3422 server.go:164] unrecognized key: Accelerators
Apr 27 03:06:46 k8s-agentpool1-40525011-0 systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Apr 27 03:06:46 k8s-agentpool1-40525011-0 systemd[1]: Stopped Kubelet.

```

https://github.com/Azure/acs-engine/blob/v0.16.0/pkg/acsengine/defaults-kubelet.go#L109
https://github.com/kubernetes/kubernetes/pull/57384
https://github.com/kubernetes/kubernetes/commit/87dda3375b6155dca7679440321836e8ea0a6871#diff-84e72664a7cc9add01954d3a7b8cbb45L64

**Comment by karataliu** [comment]
Related #2545

cc @sozercan  @jackfrancis

**Comment by sozercan** [comment]
@jackfrancis i don't believe this applies to acs-engine yet since v1.11 (alphas for now) are not supported yet. Just something to keep in mind going forward, in k8s v1.11.x accelerators feature gate is deprecated (completely removed) so kubelet won't start if accelerators feature gate is specified, #2545 fixes this but needs approval from NVIDIA.

cc @lachie83

**Comment by jackfrancis** [comment]
We do actually have 1.11.0-alpha.1 support in acs-engine now so sounds like we should just remove this immediately for all 1.11.n and greater versions.

**Comment by karataliu** [comment]
@jackfrancis I'm testing on master branch. Yes, I think removing it from 1.11.n should be right way to go but also want to make sure this aligns with #2545 .

**Comment by CecileRobertMichon** [comment]
FYI @karataliu @sozercan @jackfrancis #2814 removes the accelerators feature gate for >= 1.11
