### ISSUE TITLE
Make ManagedDisk default

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#2799]
Anecdotally, it's rare that folks want to build Kubernetes clusters w/ non-ManagedDisk, let's make it the default as (1) a convenience and (1) an opinionated expression of optimal cluster configuration for most scenarios.

We'll want to scour docs to ensure that we point out that ManagedDisk is the default, and to justify why.

**Comment by andyzhangx** [comment]
@jackfrancis do you mean make managed disk as default storage class? current logic is: it depends on agent pool created, if agent pool is blob basd VM, than default storage class is unmanaged, otherwise it's managed.

**Comment by jackfrancis** [comment]
@andyzhangx thanks, we'll do an audit to make sure that there aren't any VM skus that support managed storage that aren't configured for managed storage by default.

**Comment by andyzhangx** [comment]
@jackfrancis I did a PR a few months ago: [change default azure disk storage class for managed disk cluster](https://github.com/Azure/acs-engine/pull/1817) it has what you want.

**Comment by jackfrancis** [comment]
Actually @andyzhangx PR #2833 is what I'm talking about

**Comment by DonMartin76** [comment]
FWIW, we have run on `ManagedDisks` now for two weeks, and I can't say I am happier with it than with the `StorageAccount` clusters. Provisioning dynamic disks takes longer (3+ minutes instead of 1-2 minutes), and is also less calculatable in time (variance is higher). As our initial problem (the disk mounter checks *all* resource groups, not just the current ones, for blobs, #2768) is not appearing in 1.10.x, we will most probably go back to `StorageAccount` to see whether our clusters are more stable and consistent that way. In addition, smaller vhd disks seem to be faster than small managed disks. And we tend to have many smaller disks than a few large ones.

**Comment by jackfrancis** [comment]
Thanks for sharing @DonMartin76! I moved your thoughts here so that other folks could see them more easily:

https://github.com/Azure/acs-engine/issues/2993
