### ISSUE TITLE
openshift: infra pods on compute nodes

### ISSUE THREAD

**Issue by jim-minter** [Azure/acs-engine#2895]
looks like registry console and asb pods x2 are being created on compute nodes - shouldn't they be on infra?

**Comment by jim-minter** [comment]
@maxamillion ptal

**Comment by maxamillion** [comment]
@jim-minter I'm honestly not sure which is considered "best practice", I'd defer to @kwoodson

**Comment by kwoodson** [comment]
@jim-minter @maxamillion, we want our infra nodes running the cluster infrastructure (routing, registry, console, etc).  This is for a few reasons

- security (isolation)
- resource protection (ram, cpu guarantees)
- fronted by an elb for flexibility, scalability, reliability

**Comment by maxamillion** [comment]
Alright, so the current situation is this:

* Registry Console is deployed via openshift-ansible's `roles/cockpit-ui` role, that uses the `registry-console` template as deployed via the openshift-ansible `roles/openshift_hosted_templates` role and that template does not have a `nodeSelector` field in it as of the openshift-ansible 3.9.29 release. I'm unsure of how to resolve this in the best way because I'm unfamiliar with the implications of adding that field to the generic template that is destined for the Service Catalog.

* The Ansible Service Broker itself is more interesting because it *should* have a `nodeSelector` as it is defined in the `oc_obj` inside the openshift-ansible playbook which is set to [ansible_service_broker_node_selector](https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.9.29-1/roles/ansible_service_broker/tasks/install.yml#L246) and that evaluates by default to [region=infra](https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.9.29-1/roles/ansible_service_broker/defaults/main.yml#L3) which should work. However, after deployment the `dc/asb` inside the OpenShift Cluster does not have a `nodeSelector` field at all as per `oc get dc/asb -n openshift-ansible-service-broker -o yaml`. I'm still trying to find a root cause for that one.

**Comment by jim-minter** [comment]
Yes; what is the node selector in the default project in a normal openshift deployment?

**Comment by maxamillion** [comment]
That's set in [roles/openshift_hosted/tasks/create_projects.yml](https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.9.29-1/roles/openshift_hosted/tasks/create_projects.yml#L7), which appears to be set to an [empty string](https://github.com/openshift/openshift-ansible/blob/openshift-ansible-3.9.29-1/roles/openshift_hosted/defaults/main.yml#L9) but we should be able to override that if in the even that's the solution we want.

**Comment by kargakis** [comment]
The rest of the components in default are still infra (router, registry) fwiw

**Comment by maxamillion** [comment]
@kargakis fair point. Those have `nodeSelectors` in the kubernetes templates used to deploy them, which can be controlled via inventory variables in `openshift-ansible`, so ultimately this is a bug in `openshift-ansible` that I'll probably send a PR for once we decide on the path forward. I'm not a SME in this space, so I'm deferring the decision on the best course of action.

**Comment by maxamillion** [comment]
I've found the root cause of the `ansible-service-broker` issue with not applying the `nodeSelector` properly. The container image `registry.access.redhat.com/openshift3/ose-ansible:v3.9.25` has the `3.9.14` version of `openshift-ansible` (specifically the rpm N-V-R: `openshift-ansible-3.9.14-1.git.3.c62bc34.el7.noarch`). This was not expected and I had checked out a local git branch detached from the upstream git tag in order to trace what playbooks were doing, turns out the `3.9.14` version of `openshift-ansible` doesn't have a `nodeSelector` for the `ansible-service-broker` and that was added in a later revision. It was a compounded problem, I didn't realize the version of the rpm inside the ansible deployment container didn't match the version of the container image which then lead me to look at the wrong version of the source.

**Comment by maxamillion** [comment]
Unfortunately updating everything to `3.9.27` which does have version matching between RPM content and container image versions, it still didn't schedule these on the infra nodes. I'll follow up when I know more.

**Comment by kwoodson** [comment]
Is this still an issue? @jim-minter @maxamillion 


Here is the output of my latest install of 3.10:
```
[root@ocp-master-18884060-0 ~]# oc adm manage-node ocp-infra-18884060-0 --list-pods

Listing matched pods on node: ocp-infra-18884060-0

NAMESPACE                          NAME                             READY     STATUS    RESTARTS   AGE
default                            docker-registry-1-bhbcv          1/1       Running   0          1m
default                            router-1-xxmbb                   1/1       Running   0          1m
openshift-ansible-service-broker   asb-1-deploy                     1/1       Running   0          3s
openshift-metrics                  prometheus-0                     6/6       Running   0          1m
openshift-metrics                  prometheus-node-exporter-w2fxh   1/1       Running   0          1m
openshift-node                     sync-xrtc4                       1/1       Running   0          3m
openshift-sdn                      ovs-hzdfr                        1/1       Running   0          3m
openshift-sdn                      sdn-87s4g                        1/1       Running   0          3m
```

Here is the compute node:
```
[root@ocp-master-18884060-0 ~]# oc adm manage-node ocp-compute-18884060-0 --list-pods

Listing matched pods on node: ocp-compute-18884060-0

NAMESPACE           NAME                             READY     STATUS    RESTARTS   AGE
openshift-metrics   prometheus-node-exporter-f4rxk   1/1       Running   0          2m
openshift-node      sync-6d7lr                       1/1       Running   0          3m
openshift-sdn       ovs-xzstv                        1/1       Running   0          3m
openshift-sdn       sdn-rjpwk                        1/1       Running   0          3m
```

**Comment by jim-minter** [comment]
@kwoodson the above looks encouraging - do we have test coverage that would detect pods on the wrong nodes?  Some sort of whitelist approach could be nice.

**Comment by jim-minter** [comment]
@kwoodson if you look at https://github.com/Azure/acs-engine/blob/master/test/e2e/openshift/openshift_test.go#L62-L86, we check to see all the nodes are labeled as we expect.

I think we could have some more tests to do something similar with pods, e.g.:

no pods should be running on any compute host except a whitelist (e.g. the sync, sdn, whatever pods)
similar for the master host

some other pod test rules that would be nice would be: if we deployed ocp, ensure all pod images are pulled from registry.access.redhat.com (or oreg_url)
