### ISSUE TITLE
Version openshift e2e tests?

### ISSUE THREAD

**Issue by kargakis** [Azure/acs-engine#3049]
Something that was left out of the [versioning PR](https://github.com/Azure/acs-engine/pull/2908) is e2es and we hit a test version drift even before the first PR in unstable landed :)

Question: Should we version the e2e tests or try to manage versions inside the tests?

@jim-minter @pweil- @kwoodson @mjudeikis

**Comment by pweil-** [comment]
whoops.  I'd like to hope that the drift is generally small since we need to maintain backwards compatibility for at least n-1 api calls.  Famous last words though.  

In any case I'd want to reuse as much as possible in the tests.  Maybe start with an in-test handle and if it bites us again we rethink it?

**Comment by kargakis** [comment]
Yeah, I also slighlty prefer starting with in-test checks for now.

**Comment by pweil-** [comment]
I think the decision is good for now.  Please close since acs-bot will just yell at me.  Thanks

Know what?  I'm going to do it anyway...have at it acs-bot, you can't mess up my Friday!

/close

**Comment by kargakis** [comment]
lol, I am fixing this too 

I am going to keep this issue open to track the change that needs to be added for the node labels that @kwoodson hit.
