### ISSUE TITLE
[k8s 1.9.7] Pods are being scheduled with duplicate IP -> causes DNS resolution issues

### ISSUE THREAD

**Issue by tammert** [Azure/acs-engine#3121]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
Issue
---

**What version of acs-engine?**:
0.17.1
---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes

**What happened**:
When a lot of Pods get scheduled in a short amount of time (for example, after reboot), multiple Pods can 'share' the same IP. This (mainly) breaks DNS resolution for the 2nd/3rd Pod with the duplicate IP.

**What you expected to happen**:
All Pods are scheduled with their own IP, when there are no more IPs available Pods aren't scheduled.

**How to reproduce it** (as minimally and precisely as possible):
Roll out a 1.9.7 cluster with 0.17.1, create a sample deployment and scale it to 10 (or 20, 30) and look for IP duplicates.

**Anything else we need to know**:
Using default "azure" networkPlugin, deployed as a private cluster in a subnet, Docker version '17.05.*'. VMs are AD joined after deployment.

**Kubelet options**:
``/usr/local/bin/kubelet --enable-server --node-labels=kubernetes.io/role=master,kubernetes.azure.com/cluster=<rgp> --v=2 --volume-plugin-dir=/etc/kubernetes/volumeplugins --address=0.0.0.0 --allow-privileged=true --anonymous-auth=false --authorization-mode=Webhook --azure-container-registry-config=/etc/kubernetes/azure.json --cadvisor-port=0 --cgroups-per-qos=true --client-ca-file=/etc/kubernetes/certs/ca.crt --cloud-config=/etc/kubernetes/azure.json --cloud-provider=azure --cluster-dns=10.0.0.10 --cluster-domain=cluster.local --enforce-node-allocatable=pods --event-qps=0 --eviction-hard=memory.available<100Mi,nodefs.available<10%,nodefs.inodesFree<5% --feature-gates= --image-gc-high-threshold=85 --image-gc-low-threshold=80 --keep-terminated-pod-volumes=false --kubeconfig=/var/lib/kubelet/kubeconfig --max-pods=30 --network-plugin=cni --node-status-update-frequency=10s --non-masquerade-cidr=<range>/17 --pod-infra-container-image=k8s-gcrio.azureedge.net/pause-amd64:3.1 --pod-manifest-path=/etc/kubernetes/manifests --register-node=true --register-with-taints=node-role.kubernetes.io/master=true:NoSchedule``

**cluster.json**
```{
  "apiVersion": "vlabs",
  "properties": {
    "orchestratorProfile": {
      "orchestratorType": "Kubernetes",
      "orchestratorVersion": "1.9.7",
      "kubernetesConfig": {
        "dockerEngineVersion": "17.05.*",
        "clusterSubnet": "<range>/17",
        "privateCluster": {
          "enabled": true
        },
        "addons": [
          {
            "name": "tiller",
            "enabled": false
          }
        ]
      }
    },
    "masterProfile": {
      "count": 1,
      "vmSize": "Standard_F2s_v2",
      "vnetSubnetId": "<subnetId>",
      "dnsPrefix": "<prefix>",
      "vnetCidr": "<range>/17",
      "firstConsecutiveStaticIP": "<ip>"
    },
    "agentPoolProfiles": [
      {
        "name": "<name>",
        "count": 2,
        "vmSize": "Standard_D4s_v3",
        "vnetSubnetId": "<subnetId>",
        "storageProfile": "ManagedDisks",
        "availabilityProfile": "AvailabilitySet"
      }
    ],
    "linuxProfile": {
      "adminUsername": "<admin-user>",
      "ssh": {
        "publicKeys": [
          {
            "keyData": ""
          }
        ]
      }
    },
    "aadProfile": {
      "clientAppID": "",
      "serverAppID": "",
      "tenantID": "",
      "adminGroupID": ""
    },
    "servicePrincipalProfile": {
      "clientId": "",
      "secret": ""
    }
  }
}

**Comment by CecileRobertMichon** [comment]
@khenidak

**Comment by CecileRobertMichon** [comment]
@tammert have you observed this issue to be specific to private clusters? Or your example just happens to be with a private cluster?

**Comment by tammert** [comment]
@CecileRobertMichon I have 4 private clusters (DTAP), all are experiencing this issue. We have no use-case for a public cluster, so I have no idea if that has the same symptoms. 

Further experimentation showed that it wasn't only with high load; even a redeployment of a single Pod when the others were Running could end up with an IP that was already present on another Pod. Almost as if the component in charge of giving out IPs isn't properly aware of cluster state?

**Comment by sharmasushant** [comment]
@tammert On the nodes, where you observed multiple running PODs with same IP address, can you please share the following log files: 

/var/log/azure-*.log
/run/azure-*.json

**Comment by tammert** [comment]
Currently, IP 10.40.0.58 has been allocated twice; you can also see this in the attached `azure-vnet.json` file. The second Pod with IP 10.40.0.58 was created about 5 hours ago, which would be around 16:45 in the logs.

[azure-vnet.log](https://github.com/Azure/acs-engine/files/2059831/azure-vnet.log)
[azure-vnet-ipam.log](https://github.com/Azure/acs-engine/files/2059832/azure-vnet-ipam.log)
[azure-vnet.json.txt](https://github.com/Azure/acs-engine/files/2059834/azure-vnet.json.txt)
[azure-vnet.log.1.txt](https://github.com/Azure/acs-engine/files/2059835/azure-vnet.log.1.txt)
[azure-vnet-ipam.json.txt](https://github.com/Azure/acs-engine/files/2059836/azure-vnet-ipam.json.txt)

Thanks for the assistance so far!

**Comment by khenidak** [comment]
I seen an error 
`
2018/05/31 14:28:22 [cni-net] Plugin stopped.
2018/05/31 14:28:22 SendReport failed due to [Azure CNI] HTTP Post returned statuscode 500
2018/05/31 14:28:22 [cni-net] Plugin azure-vnet version v1.0.4-1-gf0f090e.
2018/05/31 14:28:22 [cni-net] Running on Linux version 4.13.0-1018-azure (buildd@lcy01-amd64-014) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9)) #21-Ubuntu SMP Thu May 17 13:58:38 UTC 2018
2018/05/31 14:28:22 [net] Network interface: {Index:1 MTU:65536 Name:lo HardwareAddr: Flags:up|loopback} with IP addresses: [127.0.0.1/8 ::1/128]
2018/05/31 14:28:22 [net] Network interface: {Index:2 MTU:1500 Name:eth0 HardwareAddr:00:0d:3a:2a:70:79 Flags:up|broadcast} with IP addresses: [fe80::20d:3aff:fe2a:7079/64]
2018/05/31 14:28:22 [net] Network interface: {Index:3 MTU:1500 Name:docker0 HardwareAddr:02:42:7a:0a:43:b3 Flags:up|broadcast|multicast} with IP addresses: [172.17.0.1/16]
2018/05/31 14:28:22 [net] Network interface: {Index:4 MTU:1500 Name:azure0 HardwareAddr:00:0d:3a:2a:70:79 Flags:up|broadcast|multicast} with IP addresses: [10.40.0.35/17 fe80::20d:3aff:fe2a:7079/64]
2018/05/31 14:28:22 [net] Network interface: {Index:75 MTU:1500 Name:azvethb8a8646 HardwareAddr:0e:d9:39:b4:f8:f5 Flags:up|broadcast} with IP addresses: [fe80::cd9:39ff:feb4:f8f5/64]
2018/05/31 14:28:22 [net] Network interface: {Index:77 MTU:1500 Name:azveth836b96b HardwareAddr:62:ee:06:f1:ed:f5 Flags:up|broadcast} with IP addresses: [fe80::60ee:6ff:fef1:edf5/64]
2018/05/31 14:28:22 [net] Network interface: {Index:79 MTU:1500 Name:azveth61d2021 HardwareAddr:4e:da:c3:1f:c0:34 Flags:up|broadcast} with IP addresses: [fe80::4cda:c3ff:fe1f:c034/64]
2018/05/31 14:28:22 [net] Network interface: {Index:81 MTU:1500 Name:azveth9dad865 HardwareAddr:7e:a0:3c:55:72:c9 Flags:up|broadcast} with IP addresses: [fe80::7ca0:3cff:fe55:72c9/64]
2018/05/31 14:28:22 [net] Network interface: {Index:83 MTU:1500 Name:azvethc14f1a7 HardwareAddr:56:c7:22:21:14:9b Flags:up|broadcast} with IP addresses: [fe80::54c7:22ff:fe21:149b/64]
2018/05/31 14:28:22 [net] Network interface: {Index:85 MTU:1500 Name:azveth257cf50 HardwareAddr:6e:e7:81:3a:7b:1e Flags:up|broadcast} with IP addresses: [fe80::6ce7:81ff:fe3a:7b1e/64]
2018/05/31 14:28:22 [net] Network interface: {Index:87 MTU:1500 Name:azvethc554c2b HardwareAddr:02:da:b7:5f:7f:eb Flags:up|broadcast} with IP addresses: [fe80::da:b7ff:fe5f:7feb/64]
2018/05/31 14:28:22 [net] Network interface: {Index:89 MTU:1500 Name:azvethc6a2acd HardwareAddr:52:83:e4:80:ed:c6 Flags:up|broadcast} with IP addresses: [fe80::5083:e4ff:fe80:edc6/64]
2018/05/31 14:28:22 [net] Network interface: {Index:91 MTU:1500 Name:azvethc3f7268 HardwareAddr:0a:90:18:f6:27:c3 Flags:up|broadcast} with IP addresses: [fe80::890:18ff:fef6:27c3/64]
2018/05/31 14:28:22 [net] Network interface: {Index:93 MTU:1500 Name:azvethacdc0d6 HardwareAddr:76:e2:2a:81:b2:21 Flags:up|broadcast} with IP addresses: [fe80::74e2:2aff:fe81:b221/64]
2018/05/31 14:28:22 [net] Network interface: {Index:95 MTU:1500 Name:azveth75a10f3 HardwareAddr:52:31:00:c7:8c:7b Flags:up|broadcast} with IP addresses: [fe80::5031:ff:fec7:8c7b/64]
2018/05/31 14:28:22 [net] Store timestamp is 2018-05-31 14:28:22.18100695 +0200 CEST.
2018/05/31 14:28:22 [net] Restored state, &{Version:v1.0.4-1-gf0f090e TimeStamp:2018-05-31 14:28:22.184675096 +0200 CEST ExternalInterfaces:map[eth0:0xc42014c240] store:0xc42013e210 Mutex:{state:0 sema:0}}
2018/05/31 14:28:22 [cni-net] Plugin started.
`

@jackfrancis (there are multiple of these HTTP 5000 errors). Can we involve CNI folks on it?

**Comment by sharmasushant** [comment]
@tammert Thanks for sharing the logs.

@khenidak Those errors should not cause any issue as they are telemetry related.

We are looking into this.

**Comment by khenidak** [comment]
Thanks @sharmasushant -- please update this thread with whatever you find.

**Comment by sharmasushant** [comment]
@tammert It appears that on your VM, os.Stat is returning CEST time which is +200 of UTC and UpTime on your system returns time in UTC.

The problem is that the _After()_ method in standard Golib is not considering the Location while comparing the time. This is causing us to incorrectly believe that the VM was rebooted just before CNI ADD is getting called and causing us to free any existing allocations. We free allocations on reboot because PODS are supposed to go away/relocated by K8s after reboot.

We can take a fix for comparing time correctly. While we do that, can you please try to repro by changing the time back to UTC on your VMs?

Thanks,
Sushant

**Comment by tamilmani1989** [comment]
This is the PR https://github.com/Azure/azure-container-networking/pull/162 for the fix. Please track this.

**Comment by tammert** [comment]
@sharmasushant @tamilmani1989 I can confirm that when setting the timezone to UTC on all VMs, the problem is gone. Rebooting nodes now come up with all Pods having a unique IP.

Thanks so much for the quick troubleshoot and identifying the issue!
