### ISSUE TITLE
Create public IPs in the json to have in the resource group at startup time

### ISSUE THREAD

**Issue by beaudryj** [Azure/acs-engine#3261]
**Is this a request for help?**: No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**: Kubernetes

**Anything else we need to know**:

It would be really awesome if I could pre-provision static ips that I want to assign to my ingresses. This will make creating my cluster easier as I wont have to remember to create a static IP to assign to my ingress that I want to have setup in my public DNS, I can create it with the cluster.  

### Example Json

```json
{
    "apiVersion": "vlabs",
    "properties": {
      "orchestratorProfile": {
        "orchestratorType": "Kubernetes",
        "orchestratorRelease": "1.10",
      },
      "AzurePublicIPPool": {
        "dnsPrefix": "mystatictestip",
        "sku": "Standard",
        "IpAddr":"static"
      },
      "AzurePublicIPPool": {
        "dnsPrefix": "mystatictestipenv2",
        "sku": "Standard",
        "IpAddr":"static"
      },
      "AzurePublicIPPool": {
        "dnsPrefix": "mystatictestipdev2",
        "sku": "Standard",
        "IpAddr":"static"
      },
    }
  }
```

**Comment by neurot1cal** [comment]
Would also be nice to have Public IPs that are created from within the cluster to be assigned DNS names. For example, when you try to map that IP as a TrafficManager endpoint, it cannot because theres no DNS name configured;

![image](https://user-images.githubusercontent.com/11523744/41358932-40376a14-6ede-11e8-96b3-0af11c5e5dae.png)

This does work however for public IPs that are created during provisioning for API server access.

**Comment by beaudryj** [comment]
Would be cool to see this work, then maybe we could have the JSON provision a traffic manager instead and then pre-provision some service IPs to go through TM
