### ISSUE TITLE
Pod Will Not Start Because of Unexpected End of JSON Input Error

### ISSUE THREAD

**Issue by no-stupid-questions** [Azure/acs-engine#3377]
**Is this a request for help?**:

---yes

**What version of acs-engine?**:

---
Version: v0.18.3
GitCommit: 77dafcb43
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
kubernetes 1.10.4

**What happened**:
trying to create a pod on my window 10 v1803 node and I am recieving this pod sandbox error:

Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "windows-jnlp-rzbbp_jx" network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input

**What you expected to happen**:
a pod be created on my windows 10 node

**How to reproduce it** (as minimally and precisely as possible):
deploy acs-engine's kubernetes-hybrid.json file in azure, install jx onto the linux nodes, then use kubernetes plugin to spin up pods on windows nodes. created and remove about 30 builds, then the error should pop up.

**Comment by qmalexander** [comment]
Well I can confirm that I have the same issue on acs-engine version 19.1 with kubernetes running 1.10.4.

> Here is some log from c:\k\azure-vnet.log

`018/07/06 10:04:27 [net] HNSEndpointRequest POST response:<nil> err:HNS failed with error : Element not found. .
2018/07/06 10:04:27 [net] Failed to create endpoint 1deca641-eth0, err:HNS failed with error : Element not found. .
2018/07/06 10:04:27 [azure-vnet] Failed to create endpoint: HNS failed with error : Element not found. .
2018/07/06 10:04:27 [cni] Calling plugin azure-vnet-ipam DEL nwCfg:&{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet:10.240.0.0/12 Address:10.240.0.146 QueryInterval:} DNS:{Nameservers:[10.0.0.10 10.0.0.10] Domain: Search:[svc.cluster.local] Options:[]} AdditionalArgs:[{Name:EndpointPolicy Value:[123 34 69 120 99 101 112 116 105 111 110 76 105 115 116 34 58 91 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 44 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 93 44 34 84 121 112 101 34 58 34 79 117 116 66 111 117 110 100 78 65 84 34 125]} {Name:EndpointPolicy Value:[123 34 68 101 115 116 105 110 97 116 105 111 110 80 114 101 102 105 120 34 58 34 49 48 46 48 46 48 46 48 47 49 54 34 44 34 78 101 101 100 69 110 99 97 112 34 58 116 114 117 101 44 34 84 121 112 101 34 58 34 82 79 85 84 69 34 125]}]}.
2018/07/06 10:04:27 [cni] Plugin azure-vnet-ipam returned err:<nil>.
2018/07/06 10:04:27 [cni-net] ADD command completed with result:Interfaces:[{Name:eth0 Mac: Sandbox:}], IP:[{Version:4 Interface:<nil> Address:{IP:10.240.0.146 Mask:fff00000} Gateway:10.240.0.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.240.0.1}], DNS:{Nameservers:[168.63.129.16] Domain: Search:[] Options:[]} err:<nil>.
2018/07/06 10:04:27 Failed to execute network plugin, err:Failed to create endpoint: HNS failed with error : Element not found. .
2018/07/06 10:04:27 Report plugin error
2018/07/06 10:04:29 [cni] Timed out on locking store, err:Store is locked.
2018/07/06 10:04:29 [cni-net] Failed to initialize base plugin, err:Store is locked.
2018/07/06 10:04:29 Failed to start network plugin, err:Store is locked.
2018/07/06 10:04:29 Report plugin error
2018/07/06 10:04:29 SendReport failed due to [Azure CNI] HTTP Post returned statuscode 500
2018/07/06 10:04:29 [cni-net] Plugin stopped.
2018/07/06 10:04:29 [cni-net] Plugin azure-vnet version v1.0.4-1-gf0f090e.
2018/07/06 10:04:29 [cni-net] Running on windows
2018/07/06 10:04:29 [net] Network interface: {Index:7 MTU:1500 Name:Ethernet 2 HardwareAddr:00:0d:3a:b5:79:2f Flags:up|broadcast|multicast} with IP addresses: [fe80::bd16:fdc3:4fd3:af59/64 10.240.0.127/12]
2018/07/06 10:04:29 [net] Network interface: {Index:1 MTU:-1 Name:Loopback Pseudo-Interface 1 HardwareAddr: Flags:up|loopback|multicast} with IP addresses: [::1/128 127.0.0.1/8]
2018/07/06 10:04:29 [net] Network interface: {Index:6 MTU:1500 Name:vEthernet (nat) HardwareAddr:00:15:5d:6b:d6:fc Flags:up|broadcast|multicast} with IP addresses: [fe80::686f:47c2:e3f9:f3b5/64 172.20.240.1/20]
2018/07/06 10:04:29 [net] Store timestamp is 2018-07-06 08:49:44.568296 +0000 GMT.
2018/07/06 10:04:29 [net] Restored state, &{Version:v1.0.4-1-gf0f090e TimeStamp:2018-07-06 08:49:44.5613043 +0000 UTC ExternalInterfaces:map[Ethernet 2:0xc04216e0c0] store:0xc0421523c0 Mutex:{state:0 sema:0}}
2018/07/06 10:04:29 [cni-net] Plugin started.`

@jackfrancis are you able to help?

**Comment by jackfrancis** [comment]
@PatrickLang is this one of the errata we're tracking w/ Azure CNI v1.0.7?

**Comment by PatrickLang** [comment]
I think there's a good chance this is fixed in Azure CNI 1.0.7. Let's check back once that's released soon

**Comment by qmalexander** [comment]
@jackfrancis I generated and deployed using your fix. Now I get this log:

`2018/07/09 12:04:33 [cni-net] Plugin azure-vnet version v1.0.7.
2018/07/09 12:04:33 [cni-net] Running on windows
2018/07/09 12:04:33 [net] Network interface: {Index:6 MTU:1500 Name:vEthernet (Ethernet 2) HardwareAddr:00:0d:3a:b8:45:a9 Flags:up|broadcast|multicast} with IP addresses: [fe80::4162:c06d:675:cbcc/64 10.240.0.127/12]
2018/07/09 12:04:33 [net] Network interface: {Index:1 MTU:-1 Name:Loopback Pseudo-Interface 1 HardwareAddr: Flags:up|loopback|multicast} with IP addresses: [::1/128 127.0.0.1/8]
2018/07/09 12:04:33 [net] Network interface: {Index:11 MTU:1500 Name:vEthernet (nat) HardwareAddr:00:15:5d:b5:b5:76 Flags:up|broadcast|multicast} with IP addresses: [fe80::d95d:6ab9:6128:35f3/64 172.19.32.1/20]
2018/07/09 12:04:33 os.stat() for file azure-vnet.json failed with error CreateFile azure-vnet.json: The system cannot find the file specified.
2018/07/09 12:04:33 [net] Restored state, &{Version:v1.0.7 TimeStamp:0001-01-01 00:00:00 +0000 UTC ExternalInterfaces:map[] store:0xc0420f71a0 Mutex:{state:0 sema:0}}
2018/07/09 12:04:33 [cni-net] Plugin started.
2018/07/09 12:04:33 [cni-net] Processing ADD command with args {ContainerID:ef2310f8a2e6172728ae9baacdcafe2fb449b9b8092fa229ae70651a21859f60 Netns:container:bbb816051638b77fa96a091ddbd73e192e345df6c097625e9cc68cf1a4c9d853 IfName:eth0 Args:IgnoreUnknown=1;K8S_POD_NAMESPACE=i-devtest;K8S_POD_NAME=i-devtest-web-5bd7d57b75-m7bc5;K8S_POD_INFRA_CONTAINER_ID=ef2310f8a2e6172728ae9baacdcafe2fb449b9b8092fa229ae70651a21859f60 Path:/opt/azure-vnet/bin;c:\k\azurecni\bin}.
2018/07/09 12:04:33 [cni-net] Read network configuration &{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:} DNS:{Nameservers:[10.0.0.10 168.63.129.16] Domain: Search:[svc.cluster.local] Options:[]} AdditionalArgs:[{Name:EndpointPolicy Value:[123 34 69 120 99 101 112 116 105 111 110 76 105 115 116 34 58 91 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 44 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 93 44 34 84 121 112 101 34 58 34 79 117 116 66 111 117 110 100 78 65 84 34 125]} {Name:EndpointPolicy Value:[123 34 68 101 115 116 105 110 97 116 105 111 110 80 114 101 102 105 120 34 58 34 49 48 46 48 46 48 46 48 47 49 54 34 44 34 78 101 101 100 69 110 99 97 112 34 58 116 114 117 101 44 34 84 121 112 101 34 58 34 82 79 85 84 69 34 125]}]}.
2018/07/09 12:04:33 [cni-net] Creating network azure.
2018/07/09 12:04:33 [cni] Calling plugin azure-vnet-ipam ADD nwCfg:&{CNIVersion:0.3.0 Name:azure Type:azure-vnet Mode:bridge Master: Bridge:azure0 LogLevel: LogTarget: Ipam:{Type:azure-vnet-ipam Environment: AddrSpace: Subnet: Address: QueryInterval:} DNS:{Nameservers:[10.0.0.10 168.63.129.16] Domain: Search:[svc.cluster.local] Options:[]} AdditionalArgs:[{Name:EndpointPolicy Value:[123 34 69 120 99 101 112 116 105 111 110 76 105 115 116 34 58 91 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 44 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 93 44 34 84 121 112 101 34 58 34 79 117 116 66 111 117 110 100 78 65 84 34 125]} {Name:EndpointPolicy Value:[123 34 68 101 115 116 105 110 97 116 105 111 110 80 114 101 102 105 120 34 58 34 49 48 46 48 46 48 46 48 47 49 54 34 44 34 78 101 101 100 69 110 99 97 112 34 58 116 114 117 101 44 34 84 121 112 101 34 58 34 82 79 85 84 69 34 125]}]}.
2018/07/09 12:04:33 [cni] Plugin azure-vnet-ipam returned result:IP:[{Version:4 Interface:<nil> Address:{IP:10.240.0.141 Mask:fff00000} Gateway:10.240.0.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.240.0.1}], DNS:{Nameservers:[168.63.129.16] Domain: Search:[] Options:[]}, err:<nil>.
2018/07/09 12:04:33 [cni-net] Found master interface vEthernet (Ethernet 2).
2018/07/09 12:04:33 [net] Added ExternalInterface vEthernet (Ethernet 2) for subnet 10.240.0.0/12.
2018/07/09 12:04:33 [net] Save succeeded.
2018/07/09 12:04:33 [net] Creating network &{Id:azure Mode:bridge Subnets:[{Family:2 Prefix:{IP:10.240.0.0 Mask:fff00000} Gateway:10.240.0.1}] DNS:{Suffix:i-devtest.svc.cluster.local Servers:[10.0.0.10 168.63.129.16]} Policies:[{Type:EndpointPolicy Data:[123 34 69 120 99 101 112 116 105 111 110 76 105 115 116 34 58 91 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 44 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 93 44 34 84 121 112 101 34 58 34 79 117 116 66 111 117 110 100 78 65 84 34 125]} {Type:EndpointPolicy Data:[123 34 68 101 115 116 105 110 97 116 105 111 110 80 114 101 102 105 120 34 58 34 49 48 46 48 46 48 46 48 47 49 54 34 44 34 78 101 101 100 69 110 99 97 112 34 58 116 114 117 101 44 34 84 121 112 101 34 58 34 82 79 85 84 69 34 125]}] BridgeName:azure0 Options:map[]}.
2018/07/09 12:04:33 [net] HNSNetworkRequest POST request:{"Name":"azure","Type":"l2bridge","Subnets":[{"AddressPrefix":"10.240.0.0/12","GatewayAddress":"10.240.0.1"}],"DNSSuffix":"i-devtest.svc.cluster.local","DNSServerList":"10.0.0.10,168.63.129.16"}
2018/07/09 12:04:33 [net] HNSNetworkRequest POST response:&{Id:fb407a40-6162-42f2-9966-739e36f223d1 Name:azure Type:l2bridge NetworkAdapterName: SourceMac: Policies:[] MacPools:[{StartMacAddress:00-15-5D-D0-D0-00 EndMacAddress:00-15-5D-D0-DF-FF}] Subnets:[{AddressPrefix:10.240.0.0/12 GatewayAddress:10.240.0.1 Policies:[]}] DNSSuffix:i-devtest.svc.cluster.local DNSServerList:10.0.0.10,168.63.129.16 DNSServerCompartment:0 ManagementIP: AutomaticDNS:false} err:<nil>.
2018/07/09 12:04:43 [net] Created network azure on interface vEthernet (Ethernet 2).
2018/07/09 12:04:43 [net] Save succeeded.
2018/07/09 12:04:43 [cni-net] Created network azure with subnet 10.240.0.0/12.
2018/07/09 12:04:43 [cni-net] Creating endpoint bbb81605-eth0.
2018/07/09 12:04:43 [net] Creating endpoint &{Id:bbb81605-eth0 ContainerID:ef2310f8a2e6172728ae9baacdcafe2fb449b9b8092fa229ae70651a21859f60 NetNsPath:container:bbb816051638b77fa96a091ddbd73e192e345df6c097625e9cc68cf1a4c9d853 IfName:eth0 SandboxKey: IfIndex:0 MacAddress: DNS:{Suffix:i-devtest.svc.cluster.local Servers:[10.0.0.10 168.63.129.16]} IPAddresses:[{IP:10.240.0.141 Mask:fff00000}] Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Gw:10.240.0.1}] Policies:[{Type:EndpointPolicy Data:[123 34 69 120 99 101 112 116 105 111 110 76 105 115 116 34 58 91 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 44 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 93 44 34 84 121 112 101 34 58 34 79 117 116 66 111 117 110 100 78 65 84 34 125]} {Type:EndpointPolicy Data:[123 34 68 101 115 116 105 110 97 116 105 111 110 80 114 101 102 105 120 34 58 34 49 48 46 48 46 48 46 48 47 49 54 34 44 34 78 101 101 100 69 110 99 97 112 34 58 116 114 117 101 44 34 84 121 112 101 34 58 34 82 79 85 84 69 34 125]}] Gateways:[] Data:map[vethname:i-devtest.i-devtest-web-5bd7d57b75-m7bc5]} in network azure.
2018/07/09 12:04:43 [net] HNSEndpointRequest POST request:{"Name":"bbb81605-eth0","VirtualNetwork":"fb407a40-6162-42f2-9966-739e36f223d1","Policies":[{"ExceptionList":["10.240.0.0/12","10.240.0.0/12"],"Type":"OutBoundNAT"},{"DestinationPrefix":"10.0.0.0/16","NeedEncap":true,"Type":"ROUTE"}],"IPAddress":"10.240.0.141","DNSSuffix":"i-devtest.svc.cluster.local","DNSServerList":"10.0.0.10,168.63.129.16","PrefixLength":12}
2018/07/09 12:04:43 [net] HNSEndpointRequest POST response:&{Id:3ae53b61-8f8b-43fd-a7d2-7af30fd813a4 Name:bbb81605-eth0 VirtualNetwork:fb407a40-6162-42f2-9966-739e36f223d1 VirtualNetworkName:azure Policies:[[123 32 34 69 120 99 101 112 116 105 111 110 76 105 115 116 34 32 58 32 91 32 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 44 32 34 49 48 46 50 52 48 46 48 46 48 47 49 50 34 32 93 44 32 34 84 121 112 101 34 32 58 32 34 79 117 116 66 111 117 110 100 78 65 84 34 32 125] [123 32 34 68 101 115 116 105 110 97 116 105 111 110 80 114 101 102 105 120 34 32 58 32 34 49 48 46 48 46 48 46 48 92 47 49 54 34 44 32 34 78 101 101 100 69 110 99 97 112 34 32 58 32 116 114 117 101 44 32 34 84 121 112 101 34 32 58 32 34 82 79 85 84 69 34 32 125] [123 32 34 84 121 112 101 34 32 58 32 34 76 50 68 114 105 118 101 114 34 32 125]] MacAddress:00-15-5D-D0-D8-68 IPAddress:10.240.0.141 DNSSuffix:i-devtest.svc.cluster.local DNSServerList:10.0.0.10,168.63.129.16 GatewayAddress:10.240.0.1 EnableInternalDNS:false DisableICC:false PrefixLength:12 IsRemoteEndpoint:false Namespace:<nil>} err:<nil>.
2018/07/09 12:04:43 [net] Attaching endpoint 3ae53b61-8f8b-43fd-a7d2-7af30fd813a4 to container ef2310f8a2e6172728ae9baacdcafe2fb449b9b8092fa229ae70651a21859f60.
2018/07/09 12:04:43 [net] Failed to attach endpoint: A Compute System with the specified identifier does not exist..
2018/07/09 12:04:43 [net] Created endpoint &{Id:bbb81605-eth0 HnsId:3ae53b61-8f8b-43fd-a7d2-7af30fd813a4 SandboxKey:ef2310f8a2e6172728ae9baacdcafe2fb449b9b8092fa229ae70651a21859f60 IfName:eth0 HostIfName: MacAddress:00:15:5d:d0:d8:68 IPAddresses:[{IP:10.240.0.141 Mask:fff00000}] Gateways:[10.240.0.1] DNS:{Suffix:i-devtest.svc.cluster.local Servers:[10.0.0.10 168.63.129.16]} Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} Gw:10.240.0.1}]}.
2018/07/09 12:04:43 [net] Save succeeded.
2018/07/09 12:04:43 [cni-net] ADD command completed with result:Interfaces:[{Name:eth0 Mac: Sandbox:}], IP:[{Version:4 Interface:<nil> Address:{IP:10.240.0.141 Mask:fff00000} Gateway:10.240.0.1}], Routes:[{Dst:{IP:0.0.0.0 Mask:00000000} GW:10.240.0.1}], DNS:{Nameservers:[168.63.129.16] Domain: Search:[] Options:[]} err:<nil>.
2018/07/09 12:04:43 [cni-net] Plugin stopped.`

**Comment by PatrickLang** [comment]
what error are you getting in `kubectl describe pod …` ?

**Comment by qmalexander** [comment]
@PatrickLang I will get back to you with that.
The issue I have is that the node goes unavailable for a while and the pod gets unreachable.

**Comment by PatrickLang** [comment]
Any idea how many pods are running when it happens? Is it > 20?

**Comment by jhowardmsft** [comment]
I suspect this is fixed by https://github.com/Azure/azure-container-networking/pull/247

**Comment by ai2admin** [comment]
@jhowardmsft , how do I get the fix? I'm experiencing the same problem, to the point of giving up on acs-engine, in v.0.25.3
#4331

**Comment by jhowardmsft** [comment]
@ai2admin - That I can't answer. It's really not my area at all. I just did a spot fix and a subsequent followup, but know nothing about the release mechanism here.

**Comment by ai2admin** [comment]
@jhowardmsft , would you be so kind to provide a suggestion about whom to contact?

**Comment by jhowardmsft** [comment]
https://github.com/Azure/acs-engine/blob/master/OWNERS?

**Comment by ai2admin** [comment]
Thank you.

@CecileRobertMichon @jackfrancis @mboersma @tariq1890 could any one of you please advise on how to get the fix for "Unexpected End of JSON Input Error". I see that it is suggested as already fixed, but my environment is still prone to the problem

acs-engine v0.25.3
kubernetes v1.10.9
Windows Server 1709
Azure CNI networkmonitor v0.0.4

Thank you

**Comment by CecileRobertMichon** [comment]
@ai2admin which Azure CNI version are you using? (for the plug-in, not the network monitor). This error is coming from Azure CNI, could you please open an issue at https://github.com/Azure/azure-container-networking/?

**Comment by ai2admin** [comment]
@CecileRobertMichon it's v0.3.0. Thank you for the suggestion - will open the issue at  https://github.com/Azure/azure-container-networking/
