### ISSUE TITLE
ETCDCTL_API=3

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#3444]
For convenience, set ETCDCTL_API=3 in bash profile for both root and admin user when etcd is v3.

**Comment by CecileRobertMichon** [comment]
related to #3420

**Comment by ryanhartje** [comment]
I have some questions for completeness regarding this issue. 

I see etcd environment information coming from an `/opt/azure/containers/setup-etcd.sh` but I don't see that script in this repo. Where can I find that? Can/Should I append `1iETCDCTL_API=3` as I see in https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetesmastercustomdata.yml#L471-L481

Is there something I should be using to switch on in order to maintain backwards compatibility for etcd2 users?

**Comment by ryanhartje** [comment]
Also, is this the last task to resolve #2559 ? If so this PR should close 
#2559
#3420
#3444

**Comment by jackfrancis** [comment]
I don't think we've done the other work, right @CecileRobertMichon ?

**Comment by CecileRobertMichon** [comment]
No we haven't as far as I know. Some `etcdctl` commands such as `etcdctl cluster-health` will become incompatible with v3.
