### ISSUE TITLE
Installing Docker CE 18.03

### ISSUE THREAD

**Issue by santhosh-optit** [Azure/acs-engine#3458]
Hi Team, 
We have been using ACS engine to create swarm cluster with docker ce 17.06. We would like to update the docker version to 18.03. Can you please help me understand which version of ACS engine I should use? Or if there is a different procedure I should follow. Appreciate the help

**Comment by santhosh-optit** [comment]
Thank you for quick response @mwieczorek 
We are blocked then. Can we integrate external scripts to acs-engine which install latest docker version? In this case what will happen if I increase the scale set nodes? Will this script be executed while initializing new nodes so that I will get latest docker version?

**Comment by CecileRobertMichon** [comment]
Hi @santhosh-optit, you may be able to manually workaround this issue by changing a few things in https://github.com/Azure/acs-engine/blob/master/parts/k8s/kubernetescustomscript.sh#L172 and changing the `dockerEngineVersion` param after generating the template... Unfortunately for now we are blocked on this because of license issues.
