### ISSUE TITLE
nvidia-device-plugin-daemonset pods w/ high memory + CPU

### ISSUE THREAD

**Issue by jackfrancis** [Azure/acs-engine#3481]
We're seeing high utilization of `nvidia-device-plugin-daemonset` pods on clusters. We should consider resource constraining the daemonset spec.

Data TBD.

**Comment by jackfrancis** [comment]
@lachie83 @sozercan @wbuchwalter Two questions:

1) Can you confirm that we should add resource limits to https://github.com/Azure/acs-engine/blob/master/parts/k8s/addons/kubernetesmasteraddons-nvidia-device-plugin-daemonset.yaml
2) Anyone care to volunteer some recommended limits that we can start testing against?

**Comment by wbuchwalter** [comment]
@jackfrancis This high utilization happened because their was a mismatch between `nvidia-device-plugin-daemonset` version and k8s version. The plugin kept trying to register the device and failed.
This would not happen with matching version.

If we still want to add limits, we can use the official ones: https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/device-plugins/nvidia-gpu/daemonset.yaml#L44

**Comment by jackfrancis** [comment]
Thanks @wbuchwalter!

I think we should adopt those limits, @lachie83 @sozercan, any dissenting opinions there?

**Comment by sozercan** [comment]
sgtm! 👍
