### ISSUE TITLE
Can not scale up using acs-engine 

### ISSUE THREAD

**Issue by gdbgit** [Azure/acs-engine#3533]
**Is this a request for help?**:

---Yes

**Is this an ISSUE or FEATURE REQUEST?** (choose one):

---ISSUE

**What version of acs-engine?**:

---Version: v0.19.1
GitCommit: f50fe5fe
GitTreeState: clean

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes,

 Version: v1.8.3
Git commit:
ec1d7de4456e6a397c7f931f0a2bfc74a6ca2e9c 

**What happened**:
When scale up to 17 nodes, the VMs didn’t provision successfully due to some issues at CRP end and the deployment aborted. The extension deployment didn’t start which cause kubelet related service didn’t get installed properly on agent nodes. When scaled down, the script will return error ‘cannot find node-xx’. Could you please help let us know how to mitigate this?
Reference case: 118072418639291
Reference engineer: shuanglu

**What you expected to happen**:
scale successful

**How to reproduce it** (as minimally and precisely as possible):
assign var then run command:
acs-engine scale \
    --subscription-id $SUBSCRIPTION_ID \
    --resource-group $RESOURCE_GROUP \
    --location $LOCATION \
    --deployment-dir $DEPLOYMENT_DIR \
    --new-node-count $NEW_NODE_COUNT \
    --node-pool $NODE_POOL \
    --master-FQDN $FQDN

**Anything else we need to know**:
Nothing

**Comment by jackfrancis** [comment]
@gdbgit could you retry the original scale command? Given that acs-engine doesn't really provide cluster lifecycle/state enforcement, working around transient Azure errata is annoying and difficult in these cases. Generally, a scale/upgrade that fails in the way you describe can be retried a few times. If in fact the root cause issue is temporary Azure service disruption, the upgrade operation (which under the hood is an ARM resource group deployment against the pre-existing resource group that the cluster was created in) should eventually succeed.

**Comment by Shuanglu** [comment]
@jackfrancis I'm the SE looking into this case, so the workaround is to retry the scale operation again? When last time I had remote session with customer, their 1st operation is to scale up to 8 nodes but failed due to platform issue but after that they tried to scale to 16 nodes which returns success however due to the error in 1st operation, 'kubectl get nodes' cannot only find the nodes newly created in 1st operation.

**Comment by jackfrancis** [comment]
@Shuanglu it's worth a shot. I'm not sure there is a definitive workaround, but that's the first thing I'd try before moving onto more creative options.

**Comment by Shuanglu** [comment]
@jackfrancis but the 2nd operation didn't recreate the nodes newly created in the 1st failed operation which didn't get cse provisioned successfully. Shall we try to remove those nodes created in the 1st operation and retry the 2nd oprration？

**Comment by Shuanglu** [comment]
@jackfrancis I tried to reproduce the issue recently. I guess the node count was recorded in somewhere. When the 1st scale up operation failed, it created the node VM and node count was increased but  due to cse didn't get executed, the data in k8s didn't change. This makes the following operation like scale down will fail to cordon the failed node and scale up will ignore the failed node. Any idea how to mitigate this?
