### ISSUE TITLE
testOutboundConnection fails if Google DNS is blocked.

### ISSUE THREAD

**Issue by apeschel** [Azure/acs-engine#3563]
**Is this a request for help?**:

I can create a quick patch, but review will be needed.

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

---

**What version of acs-engine?**:
Master (v0.20.2)

---

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes only.

**What happened**:
testOutboundConnection fails if the VNET has been configured to block DNS traffic to Google DNS. 

**What you expected to happen**:
The check doesn't make much sense as implemented for a couple of reasons:

1) Not sure it make sense to assume that every ACS cluster will be route-able to the internet.

2) Typically a cluster will not be using Google's DNS, but instead whatever DNS is configured for the VNET.

If a test is really needed to verify the outbound connection, it would make more sense to check ports 80 and 443. These ports are used to pull docker images and are much more likely to actually be needed by the cluster.

**How to reproduce it** (as minimally and precisely as possible):

1. Create a VNET with outgoing 53 to the internet blocked.
2. Create a new acs-engine kubernetes cluster using the existing vnet from the previous step.
3. Deploy the cluster and it will fail on the testOutboundConnection check.

**Comment by jackfrancis** [comment]
Hi @apeschel, thanks for the feedback.

In fact the test is meant to be a simple "does this cluster have access to the internet" sanity check.

At present, we don't have a reliable cluster deployment implementation that works if "outbound internet access" is not present on the VNET.

I agree that a port 53 connection against google DNS is somewhat clumsy as a stand-in for "the internet", but (1) that IP address is as good as any for reliable high availability, from an internet destination standpoint, and (2) it is a DNS resolver interface, so 53 is the right vector to test that IP against. We determined it's a good enough criteria for doing a simple sanity check.

What we're doing about this:

- We are currently building a CI pipeline that will publish pre-baked images, including all application- and OS-layer artifacts. This will allow us to revisit our criteria for requiring outbound internet access as a pre-condition to building a k8s cluster.

**Comment by apeschel** [comment]
@jackfrancis My counter argument would be that while acs engine does not have '... a reliable cluster deployment implementation that works if "outbound internet access" is not present on the VNET.', the access that is required to the internet does not include DNS to Google, and so the test is not reflective of the actual internet access required by the cluster.

Ideally this check should at least poke a socket that the cluster actually requires.

From my understanding, the internet access required by an acs-engine cluster is limited to 80 and 443, so modifying this check to use those ports instead seems like a better option.

I would propose the following implementation for `testOutboundConnection` instead.

```
function testOutboundConnection() {
    retrycmd_if_failure 20 1 3 nc -z -v index.docker.io 443 || retrycmd_if_failure 20 1 3 nc -z -v index.docker.io 80 || exit $ERR_OUTBOUND_CONN_FAIL
}
```

**Comment by jackfrancis** [comment]
@apeschel I understand your objection.

The purpose of that test is actually to be a guard against VNETs that have outbound internet access locked down. We are intentionally failing in this way, because we don't want to have to maintain a whitelist matrix of sane destinations, as you point out. Those destinations may be temporarily unavailable (we retry all of the docker image pulls, for example, to account for that) and we don't want to fail in this instance.

Your counter-argument makes perfect sense. What we are saying, more broadly is: we don't want to attempt to support surgically configured VNETs/NSGs at this time; the implementation is not ready to do that reliably. In the meantime we will fail aggressively, even if it means a false positive as you state, until we actually (1) deliver a reliable cluster operation implementation that doesn't require general outbound internet access or (2) have a maintainable way of expressing specific outbound internet access requirements.

**Comment by apeschel** [comment]
@jackfrancis Thanks for your time, the explanation is much appreciated, and this choice makes sense to me now.
