### ISSUE TITLE
Managed Disks for Master nodes

### ISSUE THREAD

**Issue by kbhattmsft** [Azure/acs-engine#371]
Right now Managed Disks are only possible for Swarm Agents whereas the Master nodes still use Storage Accounts. Please enable Managed Disks also for Master nodes.

**Comment by anhowe** [comment]
@kbhattmsft what is the scenario that managed disks will cover if it was enabled on masters?

**Comment by rjtsdl** [comment]
To clarify, i thought we have enabled managed disk for all the orchestrators' agent node. @kbhattmsft I think you were in the context of Swarm. Since @anhowe has changed the title, I will fix this one regardless of orchestrator type. Curious like Anthony, what's the scenario you need manageddisk for master nodes?

**Comment by Zenocolo** [comment]
Well, I do have a scenario where I would like to have managed disks on master nodes. I need to run postgre  database over several agent nodes, as storage I cant use Azure Fie Storage since it is using SMB which is not suitable for postgre do mount permisson issues. Therefore my best call is to install managed disks on a master and create an nfs share on it, makes sense? I tested managed disks for k8s, they only work for agent nodes, not for master.

**Comment by colemickens** [comment]
@Zenocolo er, what are you doing exactly? Kubernetes has no support for attaching or dealing with managed disks currently, and why would you be running the NFS share from the masters anyway?

Regardless of those answers, I guess I'm at a complete loss as to why we would not have managed disks for masters too. The Azure way (I know there are bumps along the way) is to get everything on VMSS + Managed DIsks, no?

**Comment by Zenocolo** [comment]
@colemickens well, at the end of the day I'm trying to define best practice for MYSQL/POSTGRE on Azure Container Service/k8s. Lets take MYSQL, there will be pods running on 3 different nodes, but they need to share data, therefore they require a persistent volume available across the 3 nodes. In the Azure world that would be Azure File Storage, but since this can only be mounted via SMB protocol this is no option (there are various articles about this). Therefore I'm trying to mount managed disk into master node and creating via LVM/NFS a share that can be resized when needed. Make sense?

Managed disk did work for me using the ACS engine (https://github.com/Azure/acs-engine/blob/master/examples/disks-managed/kubernetes-preAttachedDisks-vmas.json), not sure thats they right way to do it but this tool seems quite handy to me. When not mistaken, I think managed disk support was added in 1.6 as preview.

**Comment by colemickens** [comment]
I still don't know why you would put that on the masters though. Something
goes wrong with NFS and you've taken out your cluster.

Anyway, I highly recommend you evaluate using stateful sets for this with
normal persistent volumes and replication.

I still think we should support managed disks for masters as well as nodes,
if we don't already.

On Apr 12, 2017 5:13 AM, "Zenocolo" <notifications@github.com> wrote:

@colemickens <https://github.com/colemickens> well, at the end of the day
I'm trying to define best practice for MYSQL/POSTGRE on Azure Container
Service/k8s. Lets take MYSQL, there will be pods running on 3 different
nodes, but they need to share data, therefore they require a persistent
volume available across the 3 nodes. In the Azure world that would be Azure
File Storage, but since this can only be mounted via SMB protocol this is
no option (there are various articles about this). Therefore I'm trying to
mount managed disk into master node and creating via LVM/NFS a share that
can be resized when needed. Make sense?

Managed disk did work for me using the ACS engine (
https://github.com/Azure/acs-engine/blob/master/examples/
disks-managed/kubernetes-preAttachedDisks-vmas.json), not sure thats they
right way to do it but this tool seems quite handy to me. When not
mistaken, I think managed disk support was added in 1.6 as preview.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Azure/acs-engine/issues/371#issuecomment-293557726>,
or mute
the thread

**Comment by colemickens** [comment]
(By the way, I don't mean to be too prescriptive, just some quick suggestions. If you do end up with NFS (or Gluster or whatever) underneath the DB, I'd recommend running that on a separate specialized VM rather than overloading the master for that purpose.)

**Comment by Zenocolo** [comment]
@colemickens TNX for suggestion, I think you're right, running Gluster clyster on a seprate VM's is best option. I also tried to create with ACS engine a second agentpool "storage" with managed disks to put them into VMscaleSet, but turned out that this is still not supported, for whatever reason, so I guess running separate VMscaleSet for Gluster is the way to go.

**Comment by Zenocolo** [comment]
RE VMSS for K8S cluster: I did some research I found that VMSS is supported for DC/OS and SWARM clusters when they use managed disk, but not for K8S, may I ask for the  reason of this? (might be my missing K8S knowledge). Error message is: VirtualMachineScaleSets are not supported with Kubernetes since Kubernetes requires the ability to attach/detach disks, but in my view that is not an issue with managed disks?

**Comment by colemickens** [comment]
VMSS doesn't allow for disk attachment to single VMs. That restriction is true regardless of if they're managed disks or not.

**Comment by colemickens** [comment]
@anhowe do we intentionally not allow MD for masters?

**Comment by anhowe** [comment]
@colemickens the work for managed disks on masters has not been done yet due to resourcing.  I asked a question further up to try to understand priority: what is the scenario that we are solving if we enable managed disks on masters?

**Comment by anhowe** [comment]
Managed disks were not added due to the principle of smallest necessary change.  Please answer question at top, and we can consider re-opening.

**Comment by anhowe** [comment]
Re-opening issue, since we have now found the scenario where this makes sense to add managed disks to masters.  On June 13th, Microsoft announced that all managed disks are encrypted by SSE: https://azure.microsoft.com/en-us/blog/azure-managed-disks-sse/.

Having managed disks on Masters now means you can build a cluster that uses disks encrypted with SSE.
