### ISSUE TITLE
Query about deploying K8s cluster using acs-engine and Azure Portal

### ISSUE THREAD

**Issue by mfaizanse** [Azure/acs-engine#380]
Hi, I want to know the difference between deploying a k8s cluster on ACS using the Azure Portal and deploying by generating a template using the acs-engine and deploying it using powershell. 
I am following instructions from this [link ](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.windows.md) to deploy. 

The thing I have noted is that when deployed using azure portal, it creates a deployment with TYPE Microsoft.ContainerService and then it creates another deployment which contains the cluster resources. 
![6](https://cloud.githubusercontent.com/assets/9897945/23739203/19313a38-04bf-11e7-9329-d2a078f27041.PNG)

But when I deployed using the [instructions](https://github.com/Azure/acs-engine/blob/master/docs/kubernetes.windows.md), it did not create a deployment with TYPE Microsoftt.ContainerService, it just created deployment which contains the cluster resources. Am I missing something in this approach? The Microsoftt.ContainerService resource have some options which I need like increasing/decreasing worker agents or finding the sshMaster0 field etc..
![7](https://cloud.githubusercontent.com/assets/9897945/23739235/3eb144e2-04bf-11e7-90da-9502145ba228.PNG)

Another thing I want to ask that if I deploy using azure portal then does it use the latest commit on master branch of acs-engine git repo?

**Comment by mfaizanse** [comment]
cc: @colemickens @JiangtianLi

**Comment by colemickens** [comment]
Ack'd @mfaizanse. I'm working on getting you an answer.

**Comment by mfaizanse** [comment]
One more thing, how external loadbalancer works in azure k8s cluster? Does it load balances the traffic directly to the pods or it load balances to the VMs and the service then chooses the right endpoint?

**Comment by colemickens** [comment]
It load balances to the Service Port and `kube-proxy` writes rules that redirect traffic from "externalIP:Port" to one of the Pods running the service. This is all standard Kubernetes behavior.

**Comment by colemickens** [comment]
@mfaizanse we will add a full FAQ later, but for now:

1. ACS-Engine is not ACS, so you should not expect to see the Container Service object created. That represents a cluster owned and managed by ACS. Clusters created with ACS-Engine have no SLA or guaranteed support from the ACS team, though we provide best-effort support here on GitHub.

2. Generally speaking, features will appear in ACS-Engine before appearing in ACS. At the very least, the manual version of what ACS does will be documented for ACS-Engine. Scale up/down is a small exception due to time constraints around launching Kubernetes in ACS in February.

Going to close this out now as it hopefully answers your question. Feel free to reply if you have more questions and we can open this back up.

**Comment by mfaizanse** [comment]
Thank you @colemickens for your throughout support :)
