### ISSUE TITLE
Feature Request: Enable configuration of kube-proxy

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#3811]
**Is this an ISSUE or FEATURE REQUEST?** (choose one): FEATURE REQUEST

---
As a Kubernetes user, I would like to be able to further configure the kube-proxy `DaemonSet`. As an example, I need to set a toleration on kube-proxy so it runs on tainted nodes.

**Comment by jackfrancis** [comment]
Let's do this in the following way:

- modify the `KubernetesAddon` type struct (under both `pkg/api` and `pkg/api/vlabs`) to include a new property: `Data`
- `Data` will be a string type that is a base64-encoded yaml representation of the entire manifest definition that will be laid down on disk (say, in Sean's example, `/etc/kubernetes/addons/kube-proxy-daemonset.yaml`)
- the UX is as follows:
  - if `Data` is empty, use the existing implementation, where the `Containers` and `Config` properties capture addon-specific configuration data, which is then dispatched along the execution path to the various "view" layers in code
  - if `Data` is populated, ignore the `Containers` and `Config` properties in the `KubernetesAddon` object and instead:
    - base64-decode that yaml data during template generation
    - evolve the `GetKubernetesMasterCustomData` template func string concatenation thing so that when `kubernetesAddonSettingsInit` is invoked it is aware that addons that have been user-configured w/ `Data` payloads are the source of truth, and not the static filepath references in `pkg/acsengine/artifacts.go` under `kubernetesFeatureSetting` array for addons config

Extra credit:

  - validation so that if `Data` is present and other properties are present, we throw an error
