### ISSUE TITLE
[Kubernetes] Allocatable.pods sets to 110 regardless of agent VM size

### ISSUE THREAD

**Issue by ams0** [Azure/acs-engine#416]
For ACS- and RP-  created kubernetes clusters, agent nodes are created with the default value for allocatable pods of 110. For large VM sizes, that could be not desirable. A better way would be to calculate an ideal value for different VM sizes, and add the --max-pods flag to parts/kuberneteskubelet.service. This could be part of the OrchestratorProfile.KubernetesConfig options.

**Comment by colemickens** [comment]
I'd rather it be part of the agent pool profile, since that's where SKU is set. We could allow the user to override a default of 110 rather than try to do some magical calculation. And I'd argue that if there were a magic calculation, it would be based on mem/cpu and live in `kubelet` itself rather than here.

**Comment by ofiliz** [comment]
Note this has implications on the number of pod IP addresses that need to be assigned to the network interface when VNET-integration is enabled.

**Comment by CecileRobertMichon** [comment]
fixed via #1854, #1954 and #2618.
