### ISSUE TITLE
DC/OS cluster deployment fails with ARM template

### ISSUE THREAD

**Issue by sepiroth887** [Azure/acs-engine#419]
I tried deploying a custom VNet DC/OS cluster using the generated templates on master (gitsha 947c11a8326bb35fcdff8cf1b2b5be9dfec19e49) 

The deployment worked up until the extension waiting for master which failed due to timeout. 

Looking into the master VM it looks like that the cloud config wrote bad unit files. All DCOS related units have no newline in them which prevents the masters from spinning up correctly. 

Did I miss something or is there a problem on my end with the generation of the templates? 

For the record this was done on Windows for Bash Subsystem running Go 1.6.3 linux/amd64

**Comment by anhowe** [comment]
This looks like a new regression.  Investigating.

**Comment by anhowe** [comment]
I've successfully deployed.

Actually, what CLI are you using.  There is a known issue with older XPLat CLI's described here: https://github.com/Azure/acs-engine#deploying-with-azure-xplat-cli, that will mangle the output files similar to how you desribe.  The fix is to use the old XPlat CLI, powershell, or az CLI 2.0.

**Comment by sepiroth887** [comment]
This worked just fine using az CLI 2.0 :) Thank you !
