### ISSUE TITLE
Add windows nodes to the existing k8s cluster

### ISSUE THREAD

**Issue by avaranovich** [Azure/acs-engine#430]
I have an existing kubernetes cluster. Is there a way to add Windows nodes into the existing cluster, as I would like to start experimenting with Windows workloads.

Can I re-apply a new template, i.e. this one https://github.com/Azure/acs-engine/blob/master/examples/windows/kubernetes.json , to en existing deployment?

If I try to add the windows part to _apimodel.json_, and run acs-engine against an updated file, I am getting  _Orchestrator Kubernetes does not support Windows._ This probably means I need to update to a more recent codebase. Can I then re-build _acs-engine_ and apply it to a previosly generated _apimodel.json_? Or I need to make a backup and re-create the whole cluster from scratch?

**Comment by anhowe** [comment]
It is best if you create the whole cluster from scratch and use the latest acs-engine. 

If you are unable to, here is one approach:
1. update acs-engine
2. using the api model in the output directory that was created with this cluster, add a windows agent pool. (note that the original api model in the output directory is required because it contains the necessary key information).
3. generate the new template.
4. before deploying remove the master VM and other agent vm resources, so that only the new resources are put.

**Comment by anhowe** [comment]
Closing since this is covered by adding an agent pool with Windows.
