### ISSUE TITLE
[Kubernetes] Max number of frontend IPs

### ISSUE THREAD

**Issue by timbrand** [Azure/acs-engine#447]
I've just tried to add a Service of type LoadBalancer, and noticed that the service doesn't finish creating and keeps on Pending state.
The kube-controller-manager shows the following error:
    
`
2017-03-30T10:12:31.922013259Z E0330 10:12:31.921905       1 servicecontroller.go:665] External error while updating load balancer: network.LoadBalancersClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LoadBalancerFrontendIPConfigurationCountLimitReached" Message="A load balancer cannot have more than 10 FrontendIPConfigurations." Details=[].
`

I checked the portal, and I indeed do have 10 IPs on the LoadBalancer that has been configured with the k8s installation. I created this using the acs-engine.

So it seems that I'm unable to create a service with a public IP because the AzureLoadbalancer is limited to 10 frontend-IPs.

**Comment by colemickens** [comment]
Please contact support to raise the limit to 30.

Also, it would be great if you can file an upstream issue in Kubernetes and tag me in it? I want to see if we can:

* determine at runtime the limit on the user's account (I doubt it)
* if so, return a better error from the cloudprovider so that K8s can surface a proper error message (I don't think this will be possible, I think it will have to be an event, or we'd have to change the cloudprovider interface, but this is just off the top of my head)

**Comment by colemickens** [comment]
Also thank you for digging into the logs and triaging this, I really appreciate it!

**Comment by anhowe** [comment]
Closing since the limit was bumped to 30 (from https://github.com/Microsoft/azure-docs/issues/1238), and you should be hitting less often
