### ISSUE TITLE
Consider if `--apiserver-count` is desired on the apiserver

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#485]
I believe @aaronlevy was telling me about why `--apiserver-count` is actually counter-productive to use with apiserver.

Embarrassingly, I seem to have forgotten the exact reason why. I think it was in place to prevent flapping, but as a result, always has the 3 apiserver endpoints behind the `kubernetes` DNS VIP name even if one is down.

More importantly, I don't remember the recommended solution (maybe it was just to use DNS for the master apiservers...)

**Comment by colemickens** [comment]
Sorry to both you @aaronlevy... can you remind me the quick backstory on `--apiserver-count`? Thanks.

**Comment by aaronlevy** [comment]
Oh no worries - glad you pinged again - this almost slipped through cracks (might need to make my email/github mention filters a little less strict :)

So the upstream discussion of the behavior is here: https://github.com/kubernetes/kubernetes/issues/22609

A recent discussion we had: https://github.com/coreos/tectonic-installer/pull/136 -- which discusses the option of using a load-balancer + `--advertise-address=<loadbalancer IP>` so all api-servers just advertise their endpoint as the same thing.

The issue with the above is that advertise-address (last I looked) only supported an IP address (and in some cases that might not be stable/available). That flag may have changed, but not sure.

In the upstream issue there are a couple other side discussions for options - but in some cases you can just let the api-servers fight over the same endpoint record and it's not a huge deal. The main risk that I know about is that the kube-proxy will constantly be flushing iptables rules (because endpoints are frequently being updated), which could get expensive with a lot of services.

**Comment by colemickens** [comment]
Yes, this is perfect. The advertise-address and LB IP were exactly what I need to have jogged in my memory. We already have an ILB with a fixed IP, so we should probably move to that solution.

Thanks @aaronlevy!

**Comment by rjtsdl** [comment]
#579 , @colemickens, I have the PR ready.
@aaronlevy thx for the explanation.
