### ISSUE TITLE
Document how to increase persistent volume size

### ISSUE THREAD

**Issue by rocketraman** [Azure/acs-engine#537]
Document the procedure that should currently be used to increase (or decrease) persistent volume size.

**Comment by colemickens** [comment]
I don't think you can...

**Comment by seanknox** [comment]
Hi @rocketraman. You would need to update the PV/PVC in your pod/deployment/etc with the size you want to use. More details can be found here: https://kubernetes.io/docs/concepts/storage/volumes/

Closing as this isn't acs-engine issue.

**Comment by rocketraman** [comment]
@seanknox Thanks. The linked documentation does not say how to do this on Azure. I agree its on an acs-engine issue, but it certainly is a Kubernetes-on-Azure issue, and the only other place I can think to ask how to do this is to raise a support ticket. I'm not expecting much from the latter action.

**Comment by seanknox** [comment]
To rephrase: you can't do this with kubernetes. Modify your resources with your new disk size and kubernetes will figure out the rest.

**Comment by rocketraman** [comment]
> To rephrase: you can't do this with kubernetes. Modify your resources with your new disk size and kubernetes will figure out the rest.

Hang on -- you're saying that if I change the disk size in the deployment of the PV/PVC, Kubernetes already knows how to resize the existing Azure disks? If so, that's cool. I didn't think that was the case though...

**Comment by seanknox** [comment]
Let's say you have a deployment using dynamic disks with persistent volume claims, and let's say your deployment has ten replicas. Ten pods will spin up, each with their own PVC and attached disk that satisfies the claim request. 

If you change the deployment and it's PVC to request a bigger disk, Kubernetes will spin up ten new pods with ten PVCs and ten new disks. The old pods, PVCs, and disks will be destroyed. 

Immutable infrastructure is a core principles behind Kubernetes. Instead of tweezing changes onto a resource (pod, service, etc.) a new resource is created to replace the original.

**Comment by sylus** [comment]
Wouldn't the feature gates prevent this? I don't think this works as is.

**Comment by rocketraman** [comment]
@sylus For now this is a manual process -- support for this is coming in both Kubernetes upstream and Azure. In the interim, I've documented the manual process in #Azure in the kubernetes slack (though it may have disappeared there by now), and also here: https://stackoverflow.com/a/50536927/430128
