### ISSUE TITLE
Strictly Enforce K8S agentpool DNSPrefix to "" after June 2017

### ISSUE THREAD

**Issue by rjtsdl** [Azure/acs-engine#545]
For backwards compatibility concern, we allow K8S agentpool DNSPrefix be specified. Even though we don't do anything about it. After June 2017, we should strictly enforce user to specify "".

**Comment by rjtsdl** [comment]
#544 , this is to temporarily allow it.

**Comment by seanknox** [comment]
@rjtsdl I think release versioning can help with this. Instead of keeping obsolete config in the codebase, we can use semver to allow users to migrate when they're ready and allow us to continue improving the codebase without testing for every backwards compatibility cornercase.  cc @anhowe

**Comment by JackQuincy** [comment]
Release versioning can't solve this completely as we are going to use acs-engine in a live service. I do think this is something we can change as it is clearly a bug. but We need to be careful about it because our current live service requires this value to be set. Our next deployment will make it optional.
