### ISSUE TITLE
Switch Docker Graph driver to overlay2 or aufs

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#555]

**Comment by yuvipanda** [comment]
I just ran into this (related to #1307) - since overlay has a severe bug that causes it to run out of inodes far before it runs out of space. Combined with /var/lib/docker being on rootfs, this doesn't end well.

**Comment by yuvipanda** [comment]
We've resorted to doing the following on all our nodes:

```
#!/bin/bash
set -ex
sudo service docker stop
#sudo umount /var/lib/docker/overlay
sudo sed -i 's_/mnt_/var/lib/docker_' /etc/fstab 
sudo mount -a
sudo sed -i 's/overlay /overlay2 /' /etc/systemd/system/docker.service.d/exec_start.conf
sudo systemctl daemon-reload
sudo service docker start
sudo service kubelet restart
sudo reboot
```

**Comment by jackfrancis** [comment]
@vdice @lrdcasimir @jordanr86 @skuda PR #1433 delivers this change, would love any remarks as to your experiences with overlay2 (or pain points with existing overlay) so we can gather a consensus risk assessment of this change.

**Comment by yuvipanda** [comment]
The biggest painpoint with overlay is that it exhausts inodes far more quickly than it exhausts disk space. So your disk will end up being full despite you have a lot of 'space' left, since you run out of inodes. https://github.com/coreos/bugs/issues/264 has more info, and the doc page for 'overlay' explicitly recommends against using it https://docs.docker.com/engine/userguide/storagedriver/overlayfs-driver/

This is particularly problematic on azure, since the base disk / is only 30G by default, and that's where /var/lib/docker is mounted. I had to mount /var/lib/docker in the 'data' disk to give it more space as well.
