### ISSUE TITLE
[Feature] Agent node should support data disk as local image cache

### ISSUE THREAD

**Issue by yangl900** [Azure/acs-engine#590]
Agent node has only 30GB os disk, this doesn't work for a larger windows container image. Even on Linux, if we want to cache common base images, 30GB is not enough.

We should support agent node to cache images on data disks instead of os disk, then allow user configure a much larger data disk.

**Comment by anhowe** [comment]
Fixed in #625 by configurable OS Disk Sizes.  We want to hold off on more attached disks for two reasons: it is unclear how to partition up the disks, and in DCOS, everyone wants a different ratio, and 2, we have had stability issues with disk mount, so to keep things stable, we'll aim for configurable OS Disks sizes as the solution for this.
