### ISSUE TITLE
sshd_config messed with DC/OS template

### ISSUE THREAD

**Issue by skasturi** [Azure/acs-engine#643]
When creating a new cluster using DC/OS template, sshd_config is messed up resulting in the following lines in sshd_config file

Port 22Port 2222 

This results in leader not being chosen and inability to log into master.. 

The JSON template generated has the following, which seems to be the issue. 

\"sed -i \\\"s/^Port 22$/Port 22\\\\nPort 2222/1\\\" /etc/ssh/sshd_config\"

**Comment by JackQuincy** [comment]
Due to limitations of azure loadbalancers we need this line to allow you to ssh into your cluster on port 22 at the master loadbalancer while supporting the old model of Port 220x. We have been doing this internally for our dcos clusters for about 6 months. Though there is a known issue if the cloud init runs twice. I'm sure a more complex refer in the session could fix the run twice issue. But in general we only run custom data could init once.

Get Outlook for iOS<https://aka.ms/o0ukef>

_____________________________

**Comment by JackQuincy** [comment]
Did you run cloud init a second time?   

Also if anyone wants to update that sed command in a PR to make it so rerunning doesn't break anything that would be awesome.

**Comment by anhowe** [comment]
In a newly deployed DCOS cluster, I correctly see the lines in /etc/ssh/sshd_config:

# What ports, IPs and protocols we listen for
Port 22
Port 2222

If you still see this in the latest ACS-Engine, please re-open, and provide the model file you are using.
