### ISSUE TITLE
Add support for Storage Account Encryption

### ISSUE THREAD

**Issue by anhowe** [Azure/acs-engine#748]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** all

Add support for Storage Account Encryption for all storage accounts used by an ACS cluster.

**Comment by andscho-msft** [comment]
Since I just went through this, I thought it might be helpful to post a list of transformations I applied to the template to enabled the TDE on storages:

- Bump `apiVersionStorage` from `2015-06-15` to `2016-01-01`
- Add a `sku` field `{'name': 'Standard_RAGRS', 'tier': 'Standard'}`
- Remove `accountType` property
- Add an `encryption` property: 
```
{
   'keySource': 'Microsoft.Storage',
   'services': {
   'blob': {'enabled': True}
 }
```

Also I would vote to make this enabled by default.

**Comment by anhowe** [comment]
SSE manages the keys for the customer.
