### ISSUE TITLE
Docker log rotation policy should be configurable in API model

### ISSUE THREAD

**Issue by robbiezhang** [Azure/acs-engine#795]
**Is this a request for help?**:
Yes
---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

With [this](https://github.com/Azure/acs-engine/commit/b2cfa4cb4279beb5cc1a6900ee4a753e5a1f12bc) commit, the docker log is moved from journald to json-file, and the default log rotation is 50MB and 5 files.
It's too small, and It's better to be configurable in the API model.

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**
Kubernetes, 1.6.2

**What happened**:
The docker log rotation policy is not configurable, and the default value is too small.

**What you expected to happen**:
I can specify the log rotation policy in API model.

**How to reproduce it** (as minimally and precisely as possible):
Deploy a Kubernetes cluster with the latest acs-engine. Check the log files in /var/lib/docker/containers/.

**Anything else we need to know**:

**Comment by rjtsdl** [comment]
@anhowe 

We need to prioritize this work. 

Currently, i am thining to introduce a DockerProfile, which could be inside MasterProfile/AgentProfile. We use it to pass in docker specific parameters. And we could only expose it in vlab api.

**Comment by JackQuincy** [comment]
Could we just up the defaults? to something like 200mb max file size and  max count of 25.  then revisit how we want to make it configurable. Side note: people serious about logs should be using some aggregator like OMS which means these logs only have to live long enough for OMS to pick them up.

**Comment by amanohar** [comment]
Let's try to minimize the number of customizations/properties that are exposed in the API model as it can cause confusion. Also, MasterProfile/AgentProfile is not the right place for specifying something like DockerProfile. 

We already have a DiagnosticsProfile that was designed to be leveraged for this purposes. Right now it has VMDiagnostics and the plan to introduce ContainerDiagnostics in there that would allow options like OMS, etc. plus any other customizations.

**Comment by anhowe** [comment]
echoing Jack's comment, @robbiezhang what would be the default size you would like to see?

**Comment by robbiezhang** [comment]
Agree on Jack's recommendation. Let's do 200MB *25. BTW, is it per container limit or overall docker limit on node?

**Comment by anisimovsergey** [comment]
The policy for for the log rotation was changed recently in [this commit](https://github.com/Azure/acs-engine/commit/0b43f5c2d0f541d585dcb60db298be747759c452) 
Previously logs could occupy  50 Mb x 5 = 250 Mb now it's 200 Mb x 25 = 5000 Mb = 5 Gb  

If we run a Kubernetes cluster based on standard DS3_V2 nodes with 28 Gb disk attached to each, we can exhaust the disk space after spinning up max 5 containers theoretically. In reality, you usually end up having little bit less than 25 Gb free space and therefore you can run up to 4 containers max. Please correct me if I'm wrong. 

From my perspective it's an issue because in many projects which I'm aware of people are ruining many very small micro-services on a single VM and assuming that (according to the previous log rotation policy) that each of them can take only 250 Mb disk space for logs. Simple calculation shows that on a single DS3_V2 you could run more than 20-30 containers easily without the risk of exhausting disk space.

**Comment by agolomoodysaada** [comment]
@robbiezhang, it's per container.

**Comment by anisimovsergey** [comment]
I believe that the logs rotation policy was changed by mistake and it should be reverted back to the initial 5x50 Mb policy as soon as possible. I put an issue #1394 and created a PR #1395. I agree that this option should be configurable (as well as some other parameters) but in general some logs aggregators should be used.

**Comment by agolomoodysaada** [comment]
Is there any way to send ACS Kubernetes logs to a Logstash endpoint?
