### ISSUE TITLE
Kubernetes: Open questions regarding HA, cluster scaling, cluster upgrades and distro/security upgrades

### ISSUE THREAD

**Issue by codablock** [Azure/acs-engine#81]
I took a fast look onto the acs-engine and the generated RG templates. First thing: Thumbs up for supporting Kubernetes :) Now I got some open questions. I hope this is the right place to ask them.

1. How is HA with Kubernetes handled in ACS/acs-engine? All the docs speak about a single Kubernetes master and from what I understand from kubernetesmastercustomdata.yml, only a single non-HA master is set up. In the cluster definition doc however, there is the count field for the master profile, which suggests that HA is supported.

2. How can we later scale the number of nodes in the cluster? Should we change the number of worker nodes in the generated ARM template? Or should we regenerate the template with a new cluster definition and update the RG with the new template? Does the ACS portal provide this? If we do apply custom ARM templates, can we be sure that Azure does NOT kill/recreate anything important (e.g. route table or LB rules)?

3. How can we later upgrade to never versions of Kubernetes? Will there be any support from ACS/acs-engine or will this be a completely manual process? Will there be a difference between major/minor/patch level upgrades of Kubernetes?

4. How ca we ensure the distro has it's latest security patches and bug fixes installed?

**Comment by rgardler** [comment]
I'm sorry nobody responded to this, looks like it slipped through the net. Your questions may no longer be important to you, but for the archives I will answer and close the issue, please feel to reopen if you have follow up questions.

1) K8s support is in preview and only supports a single master. This will change to match the other orchestrators soon.

2) Similarly scaling in K8s is not currently supported. Also coming soon. Once complete you can scale by resubmitting the template with new agent count. ARM templates are idempotent so as long as you make your changes through ARM templates you should not see resources changed as side effects. Alternatively, you can use the CLI using "az acs scale" command or through the portal. 

3) Deployments using ACS Engine will always be IaaS. This means that you will be responsible for upgrades. Deployments through the published ACS in Azure will, in time, provide more management services, such as upgrade. It is our intention that scripts used to manage these upgrades will be open sourced and thus you will be able to use them on ACS Engine clusters too (though at your own risk since we will be unaware of specific customizations you have made).

4) Host VMs have security patches applied twice daily
