### ISSUE TITLE
CoreOS with DC/OS

### ISSUE THREAD

**Issue by jcrowthe** [Azure/acs-engine#83]
The DC/OS template currently generates Ubuntu virtual machines. This is currently not standard in DC/OS. This request is to modify the virtual machine OS to support CoreOS as well as Ubuntu.

As I can see, this will require modification of the cloud-config.yaml file that is parsed into the customData fields found in the template.

**Comment by colemickens** [comment]
Is this something you can contribute?

**Comment by jcrowthe** [comment]
@rgardler @colemickens I have done what I can already, and have narrowed the issue down to the cloud-config file, which is currently specific to Ubuntu. After this file is created for CoreOS, the last step is to change the Azure VM OS type, which is trivial.

It comes down to this cloud-config file which is extremely specific to Ubuntu right now, and I need someone with more experience to assist.

**Comment by anhowe** [comment]
Generally our pattern is to use CustomData to deliver the files, and then use a CSE (custom script extension for the provisioning).  With Ubuntu, we were able to skip the CSE since customData was the cloud init.  I'm not familiar with how customData gets transformed in CoreOS on Azure, but if it is only used for transfer of payload, you will need to add the CSE.  My recommendation here would be to experiment with a single CoreOS VM on Azure and learn how to correctly deliver and execute a script on  CoreOS.  My project for learning this approach on Ubuntu is here and you can probably modify it to learn how to do this for CoreOS: https://github.com/anhowe/scratch/tree/master/reliableCustomScriptExtension.

**Comment by jcrowthe** [comment]
@anhowe Thanks for pointing this out as a something to look into. I have confirmed that the customData field executes properly on CoreOS without needing any extra CSE script. Process for validation is to slightly modify acs-engine to create CoreOS VMs instead of Ubuntu VMs, and see if the customData field gets executed. The process:

1. Modify `parts/dcosmastervars.t` to boot CoreOS Stable instead of UbuntuServer:
`
    "osImageOffer": "CoreOS",
    "osImagePublisher": "CoreOS",
    "osImageSKU": "Stable",
    "osImageVersion": "latest",
`
2. Regenerate `pkg/acsengine/templates.go` with `go-bindata -pkg acsengine -prefix ../../parts/ -o templates.go ../../parts/`
3. `go build acsengine`
4. Run `./acsengine examples/dcos.json` (after modifying it the example file)
5. Deploy the output template to Azure.

After all of this, I ssh'd into the master node, and confirmed that one of the commands actually executed. This picture proves that it worked:
<img width="480" alt="screen shot 2016-11-10 at 11 45 56 am" src="https://cloud.githubusercontent.com/assets/3944151/20189623/487e050a-a73b-11e6-9503-6c1e0d465fef.png">


The [dcoscustomdata184.t] file(https://github.com/Azure/acs-engine/blob/master/parts/dcoscustomdata184.t#L102) specifies that files should be written to /etc/mesosphere, and the above screenshot proves that these files are being written to the disk.

So now is the request for help. I need help with populating the customData field. While I am capable of stripping things out (such as all of the symlink creations which can't be created on the readonly mounted filesystem anyway) and the ubuntu package installs that are already built into CoreOS (such as ipset/libipset/unzip/docker), what I cannot do is add in the content that is not there. Should this deployment use etcd and locksmithd similar as the AWS deployments? What should that code look like? This is the current limit of what I can contribute.

To reiterate, we need another option besides Ubuntu, and the primary item to address is simply to change the customData content. Most enterprises do not use Ubuntu at all, so it is very hard to integrate it into our stacks. Since the acs-engine's primary target customer is the enterprise, I am requesting something for enterprises.

If I can keep helping, I will, but I see a brick wall ahead of me that requires the skills of someone with expertise in this area.

Tagging people I talked to on Slack about this: @rgardler @mhausenblas @greenage

**Comment by anhowe** [comment]
Due to prioritization, we are not able to add support for alternative OS's at this time.  You may be able to  reach out to the DCOS and associated communication channels to see if anyone can volunteer to do this.

For this PR to be accepted, it should have the following requirements:
1. work with 1, 3, and 5 masters for DCOS
2. agents and masters reliably start, and work under all scenarios supported by acs-engine
3. work with all the features exposed in acs-engine (vnet, managed disks)
4. No noticeable impact on the generated output.  For example, any work done to implement CoreOS should not change the current templates generated for Ubuntu.
5. (Stretch) Add the same OS to Kubernetes and Swarm.

**Comment by anhowe** [comment]
We are closing as won't fix, since this is out of scope for ACS-Engine.  If you feel differently, please submit the PR as described above and we can review.

**Comment by drocsid** [comment]
Seems like a strange architectural decision to use Ubuntu when other variants are using CoreOS. Bummer.

**Comment by colemickens** [comment]
What does "other variants" here mean?

**Comment by drocsid** [comment]
My bad. It's my opinion that CoreOS would provide better infrastructure for containers and dc / os,but I may have not been clear. Is there a discussion to follow in regards of the vm choice?  CoreOS has built many oss tools for the container community in general, and has a well thought out container oriented distribution. Then what makes Ubuntu vms the best docker container infrastructure?

**Comment by colemickens** [comment]
It's what our customers ask for. Personally, I'd rather deploy on CoreOS as well, but so far it honestly just hasn't mattered too much. All of the Kubernetes components run in containers anyway, and we use the upstream version of Docker. The only time the host OS has ever mattered to me was due to provisioning (with Ubuntu Trusty I had to use upstart; not a fan), or coincidentally, problems stemming from CoreOS not shipping with a number of utilities needed for various disk attachment scenarios.

I think there are other issues about CoreOS, I'd take a look at them for more information/discussion/etc.

**Comment by ams0** [comment]
I did experiment with provisioning of Swarm mode with CentOS: even if not aware of any customer-specific request, I can imagine that there could be some interest in deploying a container orchestration framework on a supported OS (RHEL). The trouble with CentOS (and RHEL, I suppose) images in Azure is that they don't include cloud-init; I wonder if that could/will change in the future (so we focus acs-engine only on cloud-init) or not (then we better just use CustomScriptForLinux extension for all OS's? CoreOS [supports that as well](https://github.com/coreos/bugs/issues/1755)).

**Comment by kishorerv25** [comment]
Is it not possible to create VMs with RHEL OS using acs engine .???

Tried to include "distro": "RedHat" in json file for generating templates with acs.
In template files it was still pointing to ubuntu image.
Modified azuredeploy.json and azuredeploy.parameters.json files with RedHat parameters.

Deployment failed with following error messages. It has created RHEL OS machines but deployment not completed.
-----

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details.
 Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict",
"message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\":

 [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'cse0'. Error message: \\\"Enable failed: failed to execute command: command terminated with exit status=127\\n[stdout]\\n\\n[stderr]\\nstat: cannot stat ‘/opt/azure/containers/provision.complete’: No such file or directory\\n\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}
-----------

[dsci@k8s-master-42914065-0 azure]$ cat cluster-provision.log
/bin/bash: /opt/azure/containers/provision.sh: No such file or directory
[dsci@k8s-master-42914065-0 azure]$ pwd
/var/log/azure
[dsci@k8s-master-42914065-0 azure]$
