### ISSUE TITLE
Kubelets should use DNS to lookup API server address

### ISSUE THREAD

**Issue by seanknox** [Azure/acs-engine#864]
In multi-master deployments, we hardcode the IP of the first master on the kubelets. If the first master is unavailable for any reason, the cluster fails, as we don't use VMSS which could replace the failed master via Azure (much like an ASG on AWS would).

Longer term, we should provision a master ILB to serve Kubernetes nodes. There are upstream [Kubernetes issues](https://github.com/Azure/acs-engine/issues/608) that are blocking us at the moment.

Short-term, we can use Azure DNS to create an CNAME record for the masters and configure the kubelets to use that for their API server. This is what cluster provisioning tools like [tack](https://github.com/kz8s/tack/blob/master/modules/route53/route53.tf#L35) do today.

**Comment by anhowe** [comment]
I just deployed a 3 master kube cluster and the IP is hardcoded to kubernetesAPIServerIP which is the ILB.

Can you please paste your model file with the secrets redacted of where you saw the hardcoded IP of Master1?

Here is the design:
1. A single master deployment is hardcoded to master 1. 
2. A 3 or 5 master case is hardcoded to the IP of the kubernetesAPIServerIP which is the Internal lb that balances across all masters.  Once #608 is fixed, this should be a pretty robust solution.
3. DNS has been not 100% reliable, so we have been using static IPs for master discovery.

**Comment by anhowe** [comment]
There are two parts to this:
 1. ACS RPv1 – ACS service is using a 1 master template that hardcodes to master1 (https://github.com/Azure/acs-engine/blob/master/examples/classic/kubernetes.classic.json)
 2. ACS-Engine – the 1 master template allows for 3 and 5 masters to be set, and 3 and 5 masters should be blocked.  The 1 master case removes ILB because of the 17 minute delay described in #608.

Here are the proposed fixes:
 1. ACS RPv1 – update https://github.com/Azure/acs-engine/blob/master/examples/classic/kubernetes.classic.json and https://github.com/Azure/acs-engine/blob/master/examples/classic/kubernetes.classic.windows.json to use 3 masters (or pick multi-templates based on master count).
 2. ACS-Engine – for 1 master scenario, adjust parameters to only allow a single master.  This ensures no-one can use this in a 3 or 5 master scenario on a single master template.
 3. ACS-Engine – once #608 is fixed (17 minute timeout) only allow connection via ILB.
