### ISSUE TITLE
templates.go is a friction point

### ISSUE THREAD

**Issue by jsilberm** [Azure/acs-engine#878]
**Is this a request for help?**:
No

---

**Is this an ISSUE or FEATURE REQUEST?** (choose one):
ISSUE

acs-engine PR's seem to stumble, especially for any changes in "/parts", unless "/pkg/acs-engine/templates.go" is also included in the PR.

What if "templates.go" was included in .gitignore?
Would that solve the problem?
Would it break anything?

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)**

**What happened**:

PRs fail to pass, unless "templates.go" is included.

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by xtophs** [comment]
+1

**Comment by JackQuincy** [comment]
We vendor acs-engine in our service. It makes it a lot easier to use the templates in ACS-Engine/service if we can just include them in the binary. Templates.go is our way of doing that today. I to would love to not to need to include it. But to do that we need a way to be able to vendor acs-engine and be able to easily use the templates in /parts in both ACS-Engine and the code vendoring ACS-Engine.

**Comment by xtophs** [comment]
Any chance you could you run `go generate` before you vendor? I've talked to 3 people today that stopped working on PRs because the friction and the delays from having to merge `template.go` is too much to deal with. 

It seems like adding `go generate` to the script that handles vendoring would be an easy fix and remove what's probably the biggest hurdle to working with PRs. 
 
I understand it's probably a little more than just adding a line to a script, but it seems like it's a little price to pay to get much better participation. Anything we can do to help to help you manage vendoring while still enabling automerge for checkins?

**Comment by JackQuincy** [comment]
@anhowe @amanohar @colemickens  Thoughts?

**Comment by anhowe** [comment]
Yes, I agree with the feature, we just need to make sure we cover ACS RP scenario Jack mentions above.

**Comment by JackQuincy** [comment]
We would have to run it after we vendor. Because to run it before means it is still checked in/used. And if it is in use it should be kept current with what is in parts. If it just happened in make build and was git ignored would be idle. I'll look into running go generate post vendor

**Comment by seanknox** [comment]
Closed via #915. Thank you @jsilberm!
