### ISSUE TITLE
Properly escape single quotes in custom template data

### ISSUE THREAD

**Issue by jmspring** [Azure/acs-engine#917]
**Is this a request for help?**: 
No

**Is this an ISSUE or FEATURE REQUEST?** (choose one): 
Issue

**Orchestrator and version (e.g. Kubernetes, DC/OS, Swarm)** 
All - spotted in DCOS

**What happened**:
Adding a script which contains a single quote to any template custom data  will result in ARM complaining when doing a base64 encode of the data.

**What you expected to happen**:
acs-engine should properly escape single quotes in the manner ARM requires.

**How to reproduce it** (as minimally and precisely as possible):
Add the following in, say, dcoscustomdata190.t (could be any of the K8s templates as well):

```
- content: |
    #!/bin/bash
    DEVICE="/dev/sdb"
    DEVICE_BASE_NAME=`echo $DEVICE | awk -F"/" '{print $3}'`
  owner: root
  path: "/opt/azure/containers/ephemeral-disk-setup.sh"
  permissions: '0744'
```

**Comment by colemickens** [comment]
Unfortunately, it's not really possible because of how we use ARM Template functions.

`"customData": "[base64(concat('#cloud-config', variables('some_template_var'), '...'))]"`

As you can see, the single quote is part of the syntax that wraps the customData. It's generally simplist to just use double quotes and escape accordingly.

I think @anhowe had a special placeholder that would allow you to insert a single quote, but I can't find a reference to that syntax.

**Comment by anhowe** [comment]
search for "singleQuote" to see how we use variables('singleQuote')

**Comment by CecileRobertMichon** [comment]
Can we close this issue @jmspring?

**Comment by jmspring** [comment]
Yes.
