### ISSUE TITLE
cloudprovider backoff is only configured on master

### ISSUE THREAD

**Issue by colemickens** [Azure/acs-engine#981]
Is this intentional? I thought there had been throttling issues just from the nodes querying too often as well?

**Comment by jackfrancis** [comment]
Verified that this is an error. On a recently deployed cluster with backoff configured, the master looks like this:

```
azureuser@k8s-master-42301518-0:~$ sudo cat /etc/kubernetes/azure.json | grep 'cloudProviderBackoff'
    "cloudProviderBackoff": true,
    "cloudProviderBackoffRetries": 6,
    "cloudProviderBackoffExponent": 1.5,
    "cloudProviderBackoffDuration": 6,
    "cloudProviderBackoffJitter": 1,
```

And its nodes look like this:

```
azureuser@k8s-pool1-42301518-0:~$ sudo cat /etc/kubernetes/azure.json | grep 'cloudProviderBackoff'
    "cloudProviderBackoff": ,
    "cloudProviderBackoffRetries": ,
    "cloudProviderBackoffExponent": ,
    "cloudProviderBackoffDuration": ,
    "cloudProviderBackoffJitter": ,

```

This was not intentional; the inference is that the population of `azure.json` values is distinct for the master and node VMs. @colemickens Does it make sense that master/nodes would have distinct configuration flows in this case?
